### ISSUE TITLE
Configuration option to disable automatic startup at boot is not honoured.

### ISSUE THREAD

**Issue by dreirund** [SchildiChat/SchildiChat-android#104]
**Is your feature request related to a problem? Please describe.**  
*A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]*

It is very annoying that whenever I start up my android device, the SchildiChat which I have installed there does automatically start up although I do not want to use it in that session.

**Describe the solution you'd like**  
*A clear and concise description of what you want to happen.*

I wish for an option in the settings where startup at boot can be disabled.

**Describe alternatives you've considered**  
*A clear and concise description of any alternative solutions or features you've considered.*

I have tried the [App "Autostarts"](https://f-droid.org/en/packages/com.elsdoerfer.android.autostarts/) and disabled there that SchildiChat should start up on System Startup, but that setting always gets reset to enabled.

**Comment by SpiritCroc** [comment]
For the F-Droid variant and if you do not use unified push, you can disable it at "Settings / Notifications / Start on boot". Apart from that, you may also go to "Settings / Notifications" and disable "Enable notifications for this session".

**Comment by dreirund** [comment]
Hey thanks,

> For the F-Droid variant and if you do not use unified push, you can
> disable it at "Settings / Notifications / Start on boot".

I have this setting _disabled_ but the app still starts up on boot,
which I see that it shows up a notification on new messages.

Seems that this option does not do what it should?

So, how can I really prevent the app from starting up on boot?

> Apart from
> that, you may also go to "Settings / Notifications" and disable
> "Enable notifications for this session".

Yes, but this would mean I won't see notifications after I have started
the app manually, what I want.

**Comment by SpiritCroc** [comment]
> I have this setting _disabled_ but the app still starts up on boot, which I see that it shows up a notification on new messages. Seems that this option does not do what it should? So, how can I really prevent the app from starting up on boot?

Sounds like a bug, could you test if the same happens with Element?
Edit: just saw https://github.com/vector-im/element-android/issues/4906 - please link upstream issues here too.

**Comment by dreirund** [comment]
I add

#### System information:

Android 11 (in detail: "[crDroid](https://github.com/ShihabZzz/Releases/releases)" (a Google-free operating system), version string as from the ZIP file: `11.0-20210522-markw-v7.6`).

> Edit: just saw [vector-im#4906](/vector-im/element-android/issues/4906) - please link upstream issues here too.

Ah OK, I did not know that "Element" is still upstream for "SchildiChat", I thought they are individual projects.
