### ISSUE TITLE
External camera support for video call

### ISSUE THREAD

**Issue by MikkoAtWork** [SchildiChat/SchildiChat-android#108]
Currently WebRtcCall searches only for cameras that are either front-facing or back-facing. Since Android supports also external cameras, it might be useful to expose those to the app.
I have made a small patch for that (Tested only on Android Cuttlefish emulated device)
https://github.com/MikkoAtWork/SchildiChat-android/commit/65cecbd907986d3d301ac9c381be12ee7b93576e

**Comment by SpiritCroc** [comment]
Sounds like it would make sense to contribute that directly to Element too

**Comment by MikkoAtWork** [comment]
Indeed that would make sense. Copy-pasted this issue to https://github.com/vector-im/element-android/issues/5046
