### ISSUE TITLE
Notification bug

### ISSUE THREAD

**Issue by Wandelstock** [SchildiChat/SchildiChat-android#11]
**Describe the bug**
When recieving a notification, every 20 seconds (or so) its gets refreshed. On smartwatches and tasker they pick the new notification and resend it.
This is very annoying, i dont know if its Element of SC

**To Reproduce**
Make a tasker profile with catching notifications (no cooldown time), make a task that sends a beep. (I use tasker for notifications of my torch)

**Expected behavior**
You get beeps till you read it

**Comment by SpiritCroc** [comment]
I don't think I have changed anything in this regard, so this is probably an Element bug (and I see this issue there too: https://github.com/vector-im/element-android/issues/1673 )
I tested now on my device by observing the notification log that I have in my Android system settings, here's what I found out:
- It only happens with the F-Droid version and not the one with google/firebase push notifications
- The notification does not lead to a new entry in the notification log, but you can see every minute that the timestamp increases, so apparently it is resent, like you described

**Comment by eoswald** [comment]
I'm having this issue too. How can I get the version with google/firebase push notifications?
