### ISSUE TITLE
In-app emojis don't follow system emojis

### ISSUE THREAD

**Issue by Miepee** [SchildiChat/SchildiChat-android#112]
**Describe the bug**
In-app emojis don't follow system emojis and instead use the same emoji set that the emoji-picker uses (Google's Android 8 emojis).

**To Reproduce**
1. Open SchildiChat
2. View an emoji in a room, or send one.

**Expected behavior**
Emojis should use the system font to draw emojis.

**Screenshots**
Top shows the emoji SchildiChat shows, bottom shows my keyboard's emoji picker.
![image](https://user-images.githubusercontent.com/38186597/155499500-8a6a3de6-b402-4830-82e3-62f81ef7f849.png)

**Smartphone (please complete the following information):**
 - Device: Honor 6x
 - OS: Android 7.0

**Additional context**
 - App version: 1.3.12.sc48 [40100750] (F-dc42d7e8)
 - Store: F-Droid
 - Homeserver: matrix.org

**Upstream relevance**
 - Does this issue exist in Element Android? 
 Yes. See https://github.com/vector-im/element-android/issues/5336

**Comment by SpiritCroc** [comment]
A couple more things that might be interesting:

- So you have a custom emoji font installed, or it just doesn't follow your Android's default one? If you have a custom one installed, how did you install it, and do other apps properly use it?
- Do you use a CustomROM, or the stock operating system that came with your device?

**Comment by Miepee** [comment]
1) I don't have a custom emoji font installed, this is my default one.
Most other apps do use these properly.
2) stock rom.
