### ISSUE TITLE
Code elements unreadable with the SC dark themes

### ISSUE THREAD

**Issue by AlbanBedel** [SchildiChat/SchildiChat-android#116]
**Describe the bug**
Using either of the SC dark/black themes all the code elements in message are just a grey block without text. Well most probably the text and background are in the same color.

**To Reproduce**
1. Have your phone in dark mode
2. Select 'SC Dark' or 'SC Black' as dark theme 
3. Look for a message with a code element.
4. Code element look empty.

**Expected behavior**
Code elements should always be readable.

**Smartphone:**
 - Device: Redmi Note 9S
 - OS: MIUI Global 12.5.4 (Android 11)

**Additional context**
 - App version: 1.3.12.sc48
 - Store: F-Droid
 - Homeserver: own

**Upstream relevance**
I assume the 'SC' themes are specific to SchildiChat. There is also a similar bug with the 'Element Black' theme that also make the user pills unreadable.

**Comment by SpiritCroc** [comment]
Looks fine here:
![device-2022-03-15-194811](https://user-images.githubusercontent.com/12481742/158449964-07b62634-1d7e-444f-ae74-972818209a8f.png)

Can you test following:
- Try out some [v1.4.4-based beta](https://schildi.chat/android/) if it's the same
- Try killing the app from settings and restart the app, while in dark mode

**Comment by AlbanBedel** [comment]
It is the same with the beta version: 
![Screenshot_2022-03-15-22-34-19-732_de spiritcroc riotx testing foss](https://user-images.githubusercontent.com/2648902/158477206-a174f5e0-2b95-48d2-ac4e-0516204e1e5b.jpg)

**Comment by SpiritCroc** [comment]
Hm. There are multiple colors in that screenshot that look off. Could there be some operating system - wide theming solution messing with the app?

**Comment by AlbanBedel** [comment]
The screenshot was with "SC Dark, colored bubbles" and the phone set to dark mode. If I set my phone to light mode and chose the "SC Dark" theme it then look like your screenshot where the code blocks have a black background. It seems my OS is messing with black backgrounds when in dark mode.

**Comment by SpiritCroc** [comment]
Yes, that seems to be the case. Some OSes have an option to "force dark theme", maybe you can check if you have such thing enabled.
