### ISSUE TITLE
Add option to customize intergration manager URL

### ISSUE THREAD

**Issue by qwerzl** [SchildiChat/SchildiChat-android#119]
**Is your feature request related to a problem? Please describe.**
People in my country have a really bad network connection to EMS. Also, I don't have the ability to add my own sticker set.

**Describe the solution you'd like**
Add an option to customize the URL of integration manager to change it to my self-hosted dimension.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by SpiritCroc** [comment]
https://github.com/vector-im/element-android/issues/2644
