### ISSUE TITLE
SchildiChat not syncing messages/rooms

### ISSUE THREAD

**Issue by jtbx** [SchildiChat/SchildiChat-android#124]
**Describe the bug**
SchildiChat will not show messages I, or anyone else sent, past a certain date. It will also not show any new rooms I joined since that date. I can send messages, but it will not show new messages sent by anyone else. I also have UnifiedPush enabled.

**To Reproduce**
I'm not sure how to reproduce it.

**Expected behavior**
SchildiChat should automatically sync all messages I and anyone else send, as well as any rooms I join.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S4 (GT-I9505)
 - OS: LineageOS 18.1 build number `lineage_jfltexx-userdebug 11 RQ3A.211001.001 178d1ee2dc`

**Additional context**
 - App version: 1.4.13.sc52 [40100820] (F-9a8efb0e)
 - Store: F-Droid main repository
 - Homeserver: matrix.im (now mtrx.nz)

**Upstream relevance**
 - A similar issue exists: https://github.com/vector-im/element-android/issues/5700

**My Matrix ID:** 

@jeremy:mtrx.nz

**Comment by jtbx** [comment]
Note: I had UnifiedPush enabled when this bug was reported.

**Comment by darkmorpher** [comment]
Is this still reproducible on current release [v1.4.34.sc58](https://github.com/SchildiChat/SchildiChat-android/releases/tag/sc_v1.4.34.sc58) ?
