### ISSUE TITLE
Links to rooms and spaces in chat don't show

### ISSUE THREAD

**Issue by noClaps** [SchildiChat/SchildiChat-android#129]
**Describe the bug**

**To Reproduce**
1. Try to link to a space in a room, by typing "#techlore:techlore.net" in the chat
2. The suggestion for the space, or any other space do not show up, whether I am in the room or not
3. Also, even if I click on one of the options, it isn't displaying in the same formatted way as it would if typed from desktop.

**Expected behavior**
- Linking to a room or space should work the same on desktop and android.
- When linking to a room or space, it should be formatted properly, as it is on desktop, instead of simply having plain text.
- Starting to type out the link with "#" should display all joined spaces and links as suggestions

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3a XL
 - OS: Android 12

**Additional context**
 - App version: 1.4.16.sc54 [40100860] (G-b59fa0de)
 - Store: Google Play
 - Homeserver: envs.net

**Upstream relevance**
 - Does this issue exist in Element Android? Yes
 - If this issue exists in Element Android, please also link the corresponding bug report (create a new one if it doesn't exist yet)
https://github.com/vector-im/element-android/issues/6242

**Comment by SpiritCroc** [comment]
- "The suggestions [...] do not show up"
- "even if I click on one of the options"

I don't understand, what do you click, if nothing shows up?

**Comment by noClaps** [comment]
No, the suggestion item for the space I'm in, such as #techlore:techlore.net, doesn't show up.

Other options, such as the rooms I'm in, show up in the list, and selecting one of them doesn't display it properly with the pill design.

**Comment by SpiritCroc** [comment]
Ah, I see. Pill design works for me :shrug: 
But I can reproduce the spaces missing. I'll leave this for upstream to fix.
