### ISSUE TITLE
Custom reactions (/react)

### ISSUE THREAD

**Issue by 10Meisterbaelle** [SchildiChat/SchildiChat-android#132]
In some Matrix clients there is a command called /react that lets you react with a message. Here is an example: 
![Screenshot_20220704-224435_SchildiChat](https://user-images.githubusercontent.com/45918080/177215047-a7e3365c-193b-4440-b8ce-41810514908d.png)

**Comment by SpiritCroc** [comment]
If you click on the emoji-plus button next to the "Like this" in your screenshot, you can enter freeform text and react with it. I don't really see the need for a specific command to achieve the same, how would you choose which message to react to using that command?

**Comment by 10Meisterbaelle** [comment]
I can’t seem to find it. Where can you enter freeform text and react with
it? For me, it only lets me select emojis.

**Comment by SpiritCroc** [comment]
![Screenshot_2022-07-05_10-08-35](https://user-images.githubusercontent.com/12481742/177281256-987c195c-f421-4c17-8792-261b3a555485.png)

Make sure you're not on an ancient version (>= 1.4.16.sc54 required).

**Comment by 10Meisterbaelle** [comment]
> Make sure you're not on an ancient version (>= 1.4.16.sc54 required).

Yes, I accidentally used an old version. I'm closing this issue.
