### ISSUE TITLE
Crash when showing files or endless loop of files

### ISSUE THREAD

**Issue by Black616Angel** [SchildiChat/SchildiChat-android#138]
**Describe the bug**
The bug happens in all the chats with puppets (WhatsApp in my case) where some non-media file were shared.
It happens when trying to open the tab for the shared files. Schildi loads a while and then the screen turns white. On the next try the app completely crashes.
Or with lots of files there is a loop.

**To Reproduce**
1. Go to a chat with shared non-media files with a puppet-bot
2. Click Three dots
3. Go to 'Room details'
4. 'Uploads'
5. 'Files'-tab 

**Expected behavior**
If there are only a few files shared, it will whitescreen first, on second try it crashes.
In a Chat with lots of files I can scroll infinetly and see the same files over and over.

**Smartphone (please complete the following information):**
 - Device: Oneplus 7 Pro
 - OS: Android 11

**Additional context**
 - App version: 1.4.20.sc55 [40100880] (F-07e45810)
 - Store: F-Droid
 - Homeserver: matrix-cyb.org

**Upstream relevance**
 - Does this issue exist in Element Android? No

**Comment by SpiritCroc** [comment]
Sorry for my late reply, I somehow missed this one.
I cannot reproduce this on v1.4.31, maybe it's fixed by now, or it's not reliably reproducible. Since I didn't touch the attachments screen much, I'd still assume this is an Element issue.

**Comment by Black616Angel** [comment]
Got the update on F-Droid today.
Issue is fixed.
