### ISSUE TITLE
Markdown enumeration changes numbers when it shouldn't

### ISSUE THREAD

**Issue by swiss01** [SchildiChat/SchildiChat-android#139]
**Describe the bug**
if you get a number from element at the beginning followed by a dot, e.g. "4. floor" schildichat converts it to "1. floor"
if you only "6." sends, an empty message arrives in the shield iChat

**To Reproduce**
1. type in Element (Iphone or Web) 3. Hello
2. send
3. Look in SchildiChat 1. Hello 

**Expected behavior**
it should arrive the same as was sent

**Screenshots**

Element
![Element](https://user-images.githubusercontent.com/77988135/181916785-1bbf49a3-715f-4fd4-af49-33925049e070.png)

SchildiChat
![SchildiChat](https://user-images.githubusercontent.com/77988135/181916783-c0d2751c-695a-4521-b9e3-5611f293d939.png)

**Smartphone (please complete the following information):**
 - Device: [OnePlus 8T]

**Additional context**
 - App version: [V1.4.20]
 - Store: [Google Play]
 - Homeserver: [HomeServcer]

**Upstream relevance**
 - Does this issue exist in Element Android? Have no Element on android. But it works on iphone

**Comment by SpiritCroc** [comment]
Might be fixed by now with v1.4.30 test build, at least it displays fine for me right now
