### ISSUE TITLE
https://github.com/vector-im/element-android/issues/2026

### ISSUE THREAD

**Issue by Rik44444** [SchildiChat/SchildiChat-android#14]
Hi,
I love Matrix, esp the focus on bridges. I would like to start recommending it to friends and family, but the Element app is really only acceptable to them if it is possible to register and login automatically with their phone number, without a password, and with sms id confirmation. So like with WhatsApp and Signal. This is a feature request to make this possible on Matrix as well, perhaps add it as an option in the login screen. According to several experts (see link below) it should be feasible, to assign randomly generated new user names and passwords to new phone numbers, and allow users to register and login without ever having to see either, so that they can just login with their phone number. If SchildiChat is able to implement this, it will automatically become my default messenger! 

https://github.com/vector-im/element-android/issues/2026

**Comment by SpiritCroc** [comment]
Hi, thanks for your interest in SchildiChat.
How I see it, this also needs changes in your homeserver software to send an SMS confirmation.
I'm not interested in implementing this feature myself, but in case it gets implemented in Element Android, SchildiChat will get it too.
