### ISSUE TITLE
homeserver `tusooa.xyz` not fully suppoerted

### ISSUE THREAD

**Issue by Satanepigone** [SchildiChat/SchildiChat-android#140]
I was trying to login using homeserver 'tusooa.xyz`.

1st try: "Sign in with Matrix ID"
Matrix ID: `@xxxxx:tusooa.xyz`
Password: `yyyyyyyy`

Error msg: "Unable to find a valid homeserver. Please check your identifier"

2nd try: "Custom server:
Address: `https://tusooa.xyz/`
  press "Continue" -> press "Sign In"
Username: `xxxxx`
Password: `yyyyyyyy`

Successfully login!

Hardware: Google Pixel 4XL
OS: Android 12 (SQ3A.220705.003.A1)
SchildiChat was installed through Goolge Play.

**Comment by SpiritCroc** [comment]
In order for the first method to work, your server needs to provide a proper .well-known/matrix/client:

Example how it should look: https://schildi.chat/.well-known/matrix/client (base url should be https://tusooa.xyz for you)
Your server returns a 404: https://tusooa.xyz/.well-known/matrix/client

**Comment by SpiritCroc** [comment]
See also https://matrix-org.github.io/synapse/latest/setup/installation.html#client-well-known-uri

**Comment by tusooa** [comment]
Well-known is NOT required as per https://spec.matrix.org/v1.4/client-server-api/#server-discovery .

>IGNORE Stop the current auto-discovery mechanism. If no more auto-discovery mechanisms are available, then the client may use other methods of determining the required parameters, such as prompting the user, or using default values.

>Make a GET request to https://hostname/.well-known/matrix/client.
>    If the returned status code is 404, then IGNORE.

We properly return a 404, so the client should use default value of tusooa.xyz .

**Comment by SpiritCroc** [comment]
Then please test and report on Element, if this issue still exists.

**Comment by SpiritCroc** [comment]
> *may* use other methods of determining the required parameters, such as prompting the user, or using default values.

Doesn't sound like it *must* use default values here though.
(Obviously would be nicer for the user if it did though. But I'll leave that to the Element people.)

**Comment by SpiritCroc** [comment]
Note to self: if this works with Element but not with SchildiChat right now, related issue: https://github.com/SchildiChat/SchildiChat-android/issues/145
