### ISSUE TITLE
No location sharing button

### ISSUE THREAD

**Issue by rhyst** [SchildiChat/SchildiChat-android#142]
**Describe the bug**
I expect there to be a location sharing button in the menu next to the chat input box and there isn't one.

**To Reproduce**
1. Go to any chat
2. Click on the paperclip icon next to the chat text input
4. See no location sharing button

**Expected behavior**
I think there should be a location sharing button.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10e
 - OS: Android 11

**Upstream relevance**
 - Does this issue exist in Element Android?
 - The button exists in element android.

Thanks for Schildichat, I really appreciate the combined view 🙇

**Comment by SpiritCroc** [comment]
App version?

**Comment by rhyst** [comment]
Ah sorry: 1.4.20.sc55

**Comment by SpiritCroc** [comment]
Please make sure you have "Enable location sharing" enabled in Settings/Preferences :)

**Comment by rhyst** [comment]
Yes, that was it. Sorry, I must have glanced over that setting a dozen times while trying to look for it. Thanks for your time.
