### ISSUE TITLE
Collapse long reply texts

### ISSUE THREAD

**Issue by bonobo7** [SchildiChat/SchildiChat-android#143]
**Is your feature request related to a problem? Please describe.**
When someone wants to reply to a long text, the whole message gets displayed again. 

**Describe the solution you'd like**
If the quote is longer than 2 lines for example, only the first line should be printed with a triple dot at the end. 

**Additional context**
![Screenshot_20220805-151402](https://user-images.githubusercontent.com/25689744/183084909-bc789a00-89ef-4474-a054-8a3ae7516a42.jpg)

**Comment by SpiritCroc** [comment]
Upstream: https://github.com/vector-im/element-android/issues/174

**Comment by SpiritCroc** [comment]
This has been implemented with rich replies recently.
