### ISSUE TITLE
Double room and user mentions when <a> object text contains another HTML object.

### ISSUE THREAD

**Issue by 0xDEADCADE** [SchildiChat/SchildiChat-android#148]
**Describe the bug**
Sending the following as HTML causes SchildiChat Android to display the room/user mention twice.
`<a href="https://matrix.to/#/%23android%3Aschildi.chat"><img src="mxc://supercable.onl/fVWStgRAiMCZVnCTOfjCYFnL" height="24"> SchildiChat Android</a>`

**To Reproduce**
1. Send an event of type m.room.message with this content:
```
{
    "body": "<a href=\"https://matrix.to/#/%23android%3Aschildi.chat\"><img src=\"mxc://supercable.onl/fVWStgRAiMCZVnCTOfjCYFnL\" height=\"24\"> SchildiChat Android</a>",
    "format": "org.matrix.custom.html",
    "formatted_body": "<a href=\"https://matrix.to/#/%23android%3Aschildi.chat\"><img src=\"mxc://supercable.onl/fVWStgRAiMCZVnCTOfjCYFnL\" height=\"24\"> SchildiChat Android</a>",
    "msgtype": "m.text"
}
```
2. See the room mention appear twice, whereas on other clients it appears once

**Expected behavior**
The room mention should appear once

**Screenshots**
![Example Screenshot](https://matrix.deadca.de/_matrix/media/r0/download/deadca.de/RqKnCqGZUnECjtQyuoUaIGDR)

**Smartphone (please complete the following information):**
 - Device: OP Nord
 - OS: Android 12, SuperiorOS Vanilla

**Additional context**
 - App version: 1.4.34.sc58 [40100910] (F-9e380ac7)
 - Store: SpiritCroc's F-Droid
 - Homeserver: matrix.deadca.de

**Upstream relevance**
 - Does this issue exist in Element Android? This issue does not exist in Element Android (1.4.32, 1.4.34)
 - If this issue exists in Element Android, please also link the corresponding bug report (create a new one if it doesn't exist yet)

**Comment by SpiritCroc** [comment]
Haven't figured out what is happening there yet, but seems to be caused by the combination of the pills processor and the inline image plugin - if one of them is disabled, it looks ok. If the pills processor does nothing, it also looks ok. If the image plugin does a minimum of loading no image, it still breaks.

**Comment by SpiritCroc** [comment]
No more pills for nested inline images to fix this case, to be included in the next release.
