### ISSUE TITLE
Schildi Light theme has a black navigation bar

### ISSUE THREAD

**Issue by ghost** [SchildiChat/SchildiChat-android#149]
**Describe the bug**
The element light theme comes with a light-coloured navigation bar. The schildi variant of that theme has a black navigation bar, which looks a bit out of place on a modern android phone for a light-mode theme.

**To Reproduce**
1. Select schildi Light theme from preferences

**Expected behavior**
Have the navigation bar coloured like the status bar.

**Screenshots**
Note the bottom edge of the screenshots. (This is gesture navigation mode, which is why the bar is so small.)

| Element Theme         | Schildi Theme     |
|-|-|
|![image](https://user-images.githubusercontent.com/97530794/190119403-74a92c04-2353-48a7-9cfe-0de7234692bb.png)|![image](https://user-images.githubusercontent.com/97530794/190119439-0c5259bf-69bb-44db-9ed3-269bf739db07.png)|

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: Android 13

**Additional context**
 - App version: 1.4.36
 - Store:  SpiritCroc's test F-Droid
 - Homeserver: -

**Upstream relevance**
 - Does this issue exist in Element Android? No

**Comment by SpiritCroc** [comment]
Should be fixed with https://github.com/SchildiChat/SchildiChat-android/commit/b777c4bf03badaad6f508e78bf69478b2abdd4cf

**Comment by ghost** [comment]
Oops, I guess I should have known you are faster with fixing this than I am to report this issue. :sweat_smile:

**Comment by SpiritCroc** [comment]
Haha. I was already preparing some builds with Element's new layout working, and your report made me realize that it's even more important there, since the new app layout enforces a white bar apparently, leading to white icons on white background otherwise :joy:
