### ISSUE TITLE
battery

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [SchildiChat/SchildiChat-android#15]
element drains the battery within a short time SchildiChat is based on element. does SchildiChat also drain the battery?

**Comment by SpiritCroc** [comment]
There are two versions of Element:
- The gplay variant, that you can get on the Google Play Store
- The F-Droid variant, which does not use Google's proprietary push notification system. This variant, accordingly, has no battery-efficient way to look for notifications, and drains your battery faster.

SchildiChat also has these two variants (with the google push notifications variant being available [from my own F-Droid repo](https://www.spiritcroc.de/android/apps/schildichat/install_from_sc_fdroid/)).
Both variants should not feature any significant difference to the respective Element variants concerning energy consumption.
