### ISSUE TITLE
Pills with underscore are shown three times

### ISSUE THREAD

**Issue by bbhtt** [SchildiChat/SchildiChat-android#156]
**Describe the bug**

Send a pill with an underscore infront for example `#_oftc_#iwd:matrix.org`, see that it is shown thrice in the UI:

**To Reproduce**

1. Send a pill with an underscore infront 

**Expected behavior**

It should be displayed only once

**Screenshots**

![image](https://user-images.githubusercontent.com/62639087/197002916-0c669640-6796-4cc9-8230-10a501f2c17e.png)

**Smartphone (please complete the following information):**
 - Device: Nokia
 - OS: Android 10

**Additional context**
 - App version: 1.5.2.sc61
 - Store: GPlay
 - Homeserver: matrix.org

**Upstream relevance**

 - Does this issue exist in Element Android?

This doesn't seem to happen with Element 1.5.2

Message content:

```
{
  "content": {
    "body": "#_oftc_#iwd:matrix.org ",
    "format": "org.matrix.custom.html",
    "formatted_body": "<a href=\"https://matrix.to/#/#_oftc_#iwd:matrix.org\">#<em>oftc</em>#iwd:matrix.org</a>",
    "msgtype": "m.text"
  }
}
```

**Comment by SpiritCroc** [comment]
Ouch. Thanks for reporting.
From my initial tests, a single underscore is not a problem, but having two of them is. Likely again another markdown library issue, comparable to https://github.com/SchildiChat/SchildiChat-android/issues/148
