### ISSUE TITLE
Custom Notification Categories

### ISSUE THREAD

**Issue by OptimusGREEN** [SchildiChat/SchildiChat-android#160]
**Is your feature request related to a problem? Please describe.**

Unable to set specific notification tones for specific chats/rooms

**Describe the solution you'd like**

The ability to set up custom notification channels so they can be applied to individual rooms.

**Describe alternatives you've considered**

**Additional context**

I know this is possible as you can create android notification channels on the fly in home assistant so you can assign different tones to different types of notifications. This would be a great feature that would effectively allow for similar to signal WhatsApp etc, the ability to set "contact tones"

**Comment by SpiritCroc** [comment]
I don't think this is really worth working on, since Android 11 introduced "conversations" , which allows the same thing (and is even targeted more at this use case), and which is already supported by SchildiChat.

**Comment by OptimusGREEN** [comment]
> I don't think this is really worth working on, since Android 11 introduced "conversations" , which allows the same thing (and is even targeted more at this use case), and which is already supported by SchildiChat.

Oh, I had no idea this was possible already. So how do I go about setting a specific notification tones to a specific room? Could you point me to any documentation on how to achieve this?

I've had a good rumble through the settings and can't see anywhere to do this. Any help would be great.

**Comment by SpiritCroc** [comment]
Conversations require you to receive a notification of that chat first. Then, longpress the notification and click the gear icon (or something like that, depending on your Android). There it should list the "conversations" above the notification channels.

**Comment by OptimusGREEN** [comment]
Cheers, 

I'm on Android 13 and have screen shotted the procedure you mention which unless I'm doing it wrong take me to the notification categories which is just the default ones. 
![Screenshot_20221110_150522_One UI Home](https://user-images.githubusercontent.com/17599575/201131525-ad1cd7f5-3da8-457f-a4dd-7b211a153e46.jpg)
![Screenshot_20221110_150538_Settings](https://user-images.githubusercontent.com/17599575/201131596-c128cc59-5414-4f2b-a770-5bc0387895e7.jpg)
![Screenshot_20221110_150547_Settings](https://user-images.githubusercontent.com/17599575/201131614-d5f7fe9a-665a-43f5-97ae-a9b37e7c9d24.jpg)

There isnt a way to set a custom notification for a specific chat.

**Comment by SpiritCroc** [comment]
Here is what it looks like for me on Android 11 (sorry for German text):

![device-2022-11-10-161347](https://user-images.githubusercontent.com/12481742/201133090-f0d36793-7a97-443f-a05d-72b1ffe62a8e.png)

I don't have any Android 13 available to test right now though. I would expect the setting should still be somewhere :thinking:

**Comment by OptimusGREEN** [comment]
Hmm,that's interesting. I've never seen that before for any app. I'll do some googling tonight and come back with my findings. Thanks 👍

**Comment by SpiritCroc** [comment]
So, I finally fixed my Android Emulator setup (it broke a while ago and I didn't care enough to debug before) and tried with Android 13, and it's just the same... maybe your OEM is doing something weird? :thinking: 

![Screenshot_20221110_163237](https://user-images.githubusercontent.com/12481742/201137553-eb0ff4d6-e0cd-4e9c-a5a6-e0a894a33fd9.png)

**Comment by OptimusGREEN** [comment]
Hi,

No idea whats going on.

I may have worded the feature request wrongly anyway, what I think should happen is when you go into a rooms settings, should be able to set custom notification tone from there.

**Comment by SpiritCroc** [comment]
... and that's something I'm not willing to implement in SchildiChat, since this functionality is already possible using standard mechanisms provided by normal Android 11+ operating systems (don't know why it doesn't show for you), so I don't see the need to implement it in SchildiChat's room settings directly... :shrug:

**Comment by OptimusGREEN** [comment]
Its the standard way all messaging apps work like signal, whatsapp etc...

**Comment by SpiritCroc** [comment]
Other apps may have it inbuilt since this was not an Android feature before 11.
I don't say I won't include such feature if anybody wants to implement it, just that I don't consider it worth it putting my time into implementing it, since an increasing amount of people will already have it either way from the operating system.

**Comment by SpiritCroc** [comment]
If it helps, here a screenrecord of me navigating an Android 13 emulator to the setting:

https://user-images.githubusercontent.com/12481742/201345952-98a93431-ff7a-42c3-9ed3-f4676615cb95.mp4

**Comment by OptimusGREEN** [comment]
Thanks for this. Still same issue here. I'd be surprised if Samsung had removed this functionality. Its a S21 I have. I've done some serious googling today and can't find any info on this.

**Comment by OptimusGREEN** [comment]
I see that my phone does in fact incorporate the conversation settings as I can find them with other apps like signal and whatsapp but that element rooms aren't showing on the s21 as 'conversations', hence why a custom tone can't be set.

I'm going to close this as it seems an upstream issue between how element and the s21 communicate or decide what notification type is in fact a 'conversation' or 'chat'. I'll create a new issue on the element repo.

Thanks for your help.
