### ISSUE TITLE
Element message bubbles (without name and icon in DM)

### ISSUE THREAD

**Issue by AnisTaluqdar** [SchildiChat/SchildiChat-android#166]
**Is your feature request related to a problem? Please describe.**

Every most popular messenger has DM chat without both side name and icon. But no matrix client has it. I will be a very cool design if it have in schildichat too.

**Describe the solution you'd like**
If you give option in Message bubbles where will have option for select element message bubbles without both side name and icon. currently in element message bubble there have receiver icon and name it will be more standard if you remove icon and name from receiver in DM. And the group should be same as now. and It can be a another option in messeage bubblt who like it.

**Describe alternatives you've considered**

Fluffychat has simmiler DM but still they have icon. I wish have a option where both side won't have icon or name in DM.

**Additional context**

**Comment by SpiritCroc** [comment]
So I don't fully understand what you want. You seem to want Element bubbles (which you can already get in Settings / Message Bubbles / Element). Then in some places of your text, you say you want names and icons in DMs, and in others you don't, so this one is not clear to me. However, this doesn't matter: We don't touch Element bubbles, our focus are SchildiChat's original dual-side bubbles. I'd rather remove Element bubbles completely than touch them.

**Comment by AnisTaluqdar** [comment]
> So I don't fully understand what you want. You seem to want Element bubbles (which you can already get in Settings / Message Bubbles / Element). Then in some places of your text, you say you want names and icons in DMs, and in others you don't, so this one is not clear to me. However, this doesn't matter: We don't touch Element bubbles, our focus are SchildiChat's original dual-side bubbles. I'd rather remove Element bubbles completely than touch them.

okay, so at least give a option for Schildichat bubble to remove icon and name in receiver side in DM.

**Comment by SpiritCroc** [comment]
> > So I don't fully understand what you want. You seem to want Element bubbles (which you can already get in Settings / Message Bubbles / Element). Then in some places of your text, you say you want names and icons in DMs, and in others you don't, so this one is not clear to me. However, this doesn't matter: We don't touch Element bubbles, our focus are SchildiChat's original dual-side bubbles. I'd rather remove Element bubbles completely than touch them.
> 
> okay, so at least give a option for Schildichat bubble to remove icon and name in receiver side in DM.

I don't understand. Schildi bubbles already hide name and avatar in DMs. (btw, you're tone might be becoming too demanding for my taste).
