### ISSUE TITLE
On app startup, SchildiChat crashes with error: "SchildiChat keeps stopping"

### ISSUE THREAD

**Issue by CLtheman1** [SchildiChat/SchildiChat-android#168]
**Describe the bug**
There came a point when SchildiChat would stop working. A box would keep popping up on my screen telling me "SchildiChat has stopped working" until I go to settings to force stop the app. Then, when I go to open SchildiChat again it "stopped responding" and would just not work. I've uninstalled it/reinstalled it and it would be OK for a while then go back to not working. On my other device(which is now broken), I haven't had this problem. Now I'm on an old Android 8.1 device where I have this problem.

**To Reproduce**
1. Wait until you've had SchildiChat on your device for a while.
2. See error(if SchildiChat tries to start, or you click on it).

**Expected behavior**
SchildiChat should open and just work.

**Screenshots**
[None]

**Smartphone (please complete the following information):**
 - Device: Generic, unknown model
 - OS: Android 8.1

**Additional context**
 - App version: 1.5.8sc62
 - Store: NeoStore
 - Homeserver: envs.net

**Upstream relevance**
 - This issue does exist in Element, and I saw 3 GitHub issues about it.
 - https://github.com/vector-im/element-android/issues/6759
 - https://github.com/vector-im/element-android/issues/6412
 - https://github.com/vector-im/element-android/issues/3879

**Comment by ItsRogueRen** [comment]
I'm having this happen as well now seemingly out of nowhere, it used to work fine until today. Also happens with Element so I'm assuming its an upstream issue
