### ISSUE TITLE
Typing ">" crashes client

### ISSUE THREAD

**Issue by ghost** [SchildiChat/SchildiChat-android#17]
**Describe the bug**

Typing `>` (without `) in a chat will make the client crash and that chat cannot be opened anymore.

**To Reproduce**
1. Go to any DM or room
2. Type the symbol '>'
3. See error

**Expected behavior**
Like on the Element client, an empty message bubble. Or like other clients, the character in question: `>`

**Smartphone**
 - Device: Xiaomi Redmi Note 5 Pro
 - OS: Android 10 (crDroid)

**Additional context**
 - App version and store: 1.0.6.sc.19 - Foxy Droid (using F-Droid repos)
 - Homeserver: matrix.org

**Comment by SpiritCroc** [comment]
Thanks, I can reproduce this on version 1.0.8.sc.21 when sending such messages with markdown formatting enabled.
