### ISSUE TITLE
duplicate reply part in a reply message after upgrade to 1.5.24.sc63-test27 from 1.5.22.sc63-test23

### ISSUE THREAD

**Issue by CoelacanthusHex** [SchildiChat/SchildiChat-android#174]
**Describe the bug**

If a message replies to another, it will have duplicate reply parts.
It seems that one is SchildiChat style and the other is Element original style.

**To Reproduce**
1. Find a reply message
2. See error

**Expected behavior**

It only has ONE reply part.

**Screenshots**

![图片](https://user-images.githubusercontent.com/43064781/218252561-87220157-7838-4c19-baa4-48b2bf9a4b87.png)

**Smartphone (please complete the following information):**
 - Device: Redmi K30S Ultra
 - OS: Lineage OS 19, Android 12

**Additional context**
 - App version: 1.5.24.sc63-test27 [40101017] (F-a48ce4b1)
 - Store: SpiritCroc's F-Droid
 - Homeserver: matrix.envs.net

**Upstream relevance**
 - Does this issue exist in Element Android? No

1.5.22.sc63-test23 works well.

**Comment by SpiritCroc** [comment]
Thanks for reporting. I fixed this today already, please update to -test29 :)

Fixed in https://github.com/SchildiChat/SchildiChat-android/commit/6a2f318c1d222a0bdab211069da9fa8937ca47d6 .

**Comment by CoelacanthusHex** [comment]
It was fixed after upgrade, Thanks!
