### ISSUE TITLE
Feature request: Remove MapBox Tracking

### ISSUE THREAD

**Issue by marek22k** [SchildiChat/SchildiChat-android#176]
**Is your feature request related to a problem? Please describe.**
Not directly. It's more of a privacy issue.

**Describe the solution you'd like**
Removing mapbox dependencies and tracking.

**Describe alternatives you've considered**
No tracking.

**Additional context**
I detected the tracker using the Warden app (https://apt.izzysoft.de/fdroid/index/apk/com.aurora.warden).

**Comment by SpiritCroc** [comment]
Have you actually observed any tracking, or could that be a false positive because some apps might use the library for tracking, but we don't?
Either way, please check for Element and ask them, I haven't touched any location rendering and I'm not planning to do so.

**Comment by marek22k** [comment]
Created issue on upstream https://github.com/vector-im/element-android/issues/8300

**Comment by marek22k** [comment]
There is an answer in the upstream issue.
