### ISSUE TITLE
Hide space-rooms in overview tab

### ISSUE THREAD

**Issue by SteffoSpieler** [SchildiChat/SchildiChat-android#177]
**Is your feature request related to a problem? Please describe.**
I have many rooms (with the same name) in multiple spaces. On the desktop (Element Desktop) I have the option to disable the option "Show all rooms" which then only shows rooms that aren't in spaces.
As you can show all spaces at the bottom, it's kinda annoying to see the rooms in multiple tabs.

**Describe the solution you'd like**
Make an option to hide (or show) all rooms (like in the Element Desktop App).

**Describe alternatives you've considered**
There is the option `Combined chat overview`, which shows rooms and direct-messages in seperate categories, as a second bottom bar. Though the state isn't saved so I always need to switch between rooms and direct-messages, when I switch to a space and back. (As there are (for me) no direct-messages in spaces.)

So this would be an option, if it wouldn't be such an annoyance.

And again, I have rooms (in different spaces) with the same name (e.g. "general"), so seeing the same name, with the same (not existing) picture, is really confusing.

**Comment by SpiritCroc** [comment]
What about disabling Settings / Preferences / Show all rooms in Home? (and maybe make sure you don't use the "new layout" from labs, which may break things and is less tested)

**Comment by SteffoSpieler** [comment]
oh wow, I didn't see that. (to be honest, finding things in the settings is kinda hard..)

I didn't even use the new layout. But yeah, that works! Thank you!
