### ISSUE TITLE
Remove sentry (already have issues)

### ISSUE THREAD

**Issue by Wjxfi** [SchildiChat/SchildiChat-android#185]
![341515.jpg](https://user-images.githubusercontent.com/113500363/225093268-f09b33ec-f006-4d8c-a9b1-d4d5d9af5b1b.jpg)

**Comment by SpiritCroc** [comment]
If you want me to do something, write something, not just paste screenshots.
Sentry should be disabled and not be doing anything, so I don't see the need to mess with the upstream codebase just to please static scanners, unless there's some proper evidence that keeping it is causing any actual (privacy or other) issue.
