### ISSUE TITLE
Url preview

### ISSUE THREAD

**Issue by feliscat** [SchildiChat/SchildiChat-android#187]
https://github.com/SchildiChat/SchildiChat-android/blob/sc/FEATURES.md lists as a feature

> Setting to also enable URL previews in encrypted chats (for users who trust their homeserver or who don't care about leaked message content in this case)

However, this isn't an option in encrypted chats. Am I missing how to enable it?

**Comment by SpiritCroc** [comment]
Settings / Labs / URL previews in encrypted chats (3rd option from the top).
