### ISSUE TITLE
Wrong message shield for deleted session

### ISSUE THREAD

**Issue by waclaw66** [SchildiChat/SchildiChat-android#188]
**Describe the bug**
When a message is sent for from a device to SchildiChat and that session is deleted afterwards, SchildiChat Android shows that message with red shield with message "Encrypted by an unverified device". The same message has grey shield in ElementAndroid with message "The authenticity of this encrypted message can't be guaranteed on this device." and in ElementWeb another message "Encrypted by a deleted session" same as SchildiChat Web.

**To Reproduce**
1. Send a message from another device
2. Log out from that device
3. See the message in SchildiChat Android.

**Expected behavior**
Grey shield with proper message

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/15554561/231075545-101962ac-4790-4b92-9994-5b3f1fc3cad6.png)

**Smartphone (please complete the following information):**
 - Device: Samsung S20 FE
 - OS: Android 13

**Upstream relevance**
 - Does this issue exist in Element Android?
No

**Comment by SpiritCroc** [comment]
Have you compared a freshly installed SchildiChat and Element with a matching Element version on this? Would surprise me if I changed that behaviour compared to upstream in any way.

**Comment by waclaw66** [comment]
Yes, versions are the same, ElementAndroid 1.5.30 and SchildiChat 1.5.30.sc66-test5.

**Comment by waclaw66** [comment]
I tried to log off and login again and the shield is grey now, same as ElementAndroid :D Bugs, bugs, bugs...
