### ISSUE TITLE
Can't spoiler links

### ISSUE THREAD

**Issue by ghost** [SchildiChat/SchildiChat-android#190]
**Describe the bug**

**To Reproduce**
Send /spoiler http://example.com
**Expected behavior**
Just spoiler with link on open
**Screenshots**
Pinned (please don't check the link)
![Screenshot_2023-04-20-09-32-06](https://user-images.githubusercontent.com/116358854/233278036-1fa6960d-734f-44ef-bb0a-ee7652a4df06.png)

**Smartphone (please complete the following information):**
 - Device: Oukitel WP5
 - OS: Android 10

**Additional context**
 - App version: 1.5.30.sc66 [40101060] (G-c63f01b4)
 - Homeserver: fb.doesnm.cc
 - Related labs settings: I don't think it's related to the lab 
**Upstream relevance**
 - Does this issue exist in Element Android? I don't know
 - If this issue exists in Element Android, please also link the corresponding bug report (create a new one if it doesn't exist yet)

**Comment by SpiritCroc** [comment]
I can reproduce this on Element as well.
In addition to fixing the hiding of the link, might make also sense to somehow disable url previews for spoilered links. Also, one would need to pay attention that the link is not clickable until the spoiler is revealed.

**Comment by doesnmisclown** [comment]
Upd: logged in the next day and hold the same message. There is no bug. It's some kind of floating bug
