### ISSUE TITLE
TURN failover?

### ISSUE THREAD

**Issue by mxwmnn** [SchildiChat/SchildiChat-android#191]
Would be awesome like in the iOS App that u can use turn.matrix.org for calls as a failover method cause my Homeserver doesn't support a own turn server.

**Comment by SpiritCroc** [comment]
Looks like we could easily cherry-pick https://github.com/vector-im/element-android/pull/5781 to get this. Are you willing to install the beta (compare test release section at https://schildi.chat/android/ ) to test this if I add it?

**Comment by mxwmnn** [comment]
Yeah, of course. :)

**Comment by SpiritCroc** [comment]
ok, can you install the latest beta (1.5.32.sc68-test1) and test/confirm:
- With Settings / Voice & Video / Allow fallback call assist server turned *off*, it still doesn't work
- With Settings / Voice & Video / Allow fallback call assist server turned *on*, it works

**Comment by mxwmnn** [comment]
Sorry I'm not into android development and i can't get it running on a server to build the sc_beta branch even with modified gradle.properties

Can u build it?

**Comment by SpiritCroc** [comment]
If you are having issues using the fdroid beta repo, these direct download links should probably work too:
- For FCM variant: https://s2.spiritcroc.de/testing/fdroid/repo/de.spiritcroc.riotx.testing.fcm_40101071.apk
- For FOSS variant: https://s2.spiritcroc.de/testing/fdroid/repo/de.spiritcroc.riotx.testing.foss_40101071.apk

**Comment by mxwmnn** [comment]
Forgot to look at ur page got it working through f-droid. 

Tested it know and works flawlessly without a turn server on the matrix Homeserver. Thanks a lot!

**Comment by mxwmnn** [comment]
The only thing to mention is, I don't get a call notification if someone calls me. Using ntfy. Messages works but no calls

**Comment by mxwmnn** [comment]
The only thing to mention is, I don't get a call notification if someone calls me. Using ntfy. Messages works but no calls

**Comment by SpiritCroc** [comment]
Why re-open? Sounds like a different issue, which is likely an upstream issue (and should thus better be tested and reported for Element if applicable).

**Comment by mxwmnn** [comment]
Sorry will report it there thanks.
