### ISSUE TITLE
Long press a message shows a different message

### ISSUE THREAD

**Issue by ghost** [SchildiChat/SchildiChat-android#194]
**Describe the bug**
When a message is selected, it displays another message
**To Reproduce**
1. Idk how I catch but I just hold message

**Expected behavior**
I must receive a message from the same author and content 

**Smartphone (please complete the following information):**
 - Device: Oukitel WP5
 - OS: Android 10

**Additional context**
 - App version: 1.5.32.sc67 [40101070] (G-56b715c4)
 - Store: Google Play
 - Homeserver: matrix.org
 - Related labs settings: I don't think it depends 

**Upstream relevance**
 - Does this issue exist in Element Android? Idk

**Comment by ghost** [comment]
Oh, I forgot video

https://github.com/SchildiChat/SchildiChat-android/assets/116358854/4e1e1823-b290-44f5-8245-75accb48eb43

**Comment by SpiritCroc** [comment]
That's interesting, haven't seen that before :thinking: 
I'd be interested in having a look if you find some clear steps how to reproduce. Also, would be very interesting if you could try if the same happens on Element as well.

**Comment by ghost** [comment]
Downloaded element: can't reproduce. Maybe it's cache bug?

**Comment by ghost** [comment]
Logged in now and hold the same message. There is no bug. It's some kind of floating bug

**Comment by SpiritCroc** [comment]
Hm, that's unfortunate for reproducing it to fix it. If anybody has some idea how to reproduce, please share :)
Thanks for testing again.
