### ISSUE TITLE
Custom emojis and sticks as in Nheko, Fluffychat and Cinny

### ISSUE THREAD

**Issue by bitokulo** [SchildiChat/SchildiChat-android#195]
**Is your feature request related to a problem? Please describe.**
It lacks custom emojis / stickers like in Nheko, Fluffychat and Cinny. To this time, it's only possible to use a server's stickers, which isn't vey accessible.

**Describe the solution you'd like**
The sticker feature of Element is absolutely lesser than custom emojis / stickers from Fluffychat/Nheko/Cinny. It should be replaced with whatever they use.

**Describe alternatives you've considered**
This feature could be added as an alternative in settings

**Additional context**
As in Cinny, a server's stickers/emojis. They can be created per account or per room, the latter can be used by anyone in the room anywhere (if they choose to per emoji pack).
![Cinny Emojis](https://github.com/SchildiChat/SchildiChat-android/assets/134810902/26a9fa15-1baf-445f-a731-fc7f4c29c9b4)

**Comment by SpiritCroc** [comment]
It's already possible to send such custom emotes and stickers using the `:shortcode:` autocompletion, as long as you do not use the wysiwyg rich text editor (which is still in labs anyways). For managing emotes and stickers, it's possible to use a different application like the ones you mentioned, and it will carry over to SchildiChat.

**Comment by bitokulo** [comment]
And how will I know which custom emojis there are ~~is~~ if there is no list? There's no graphical implementation to see nor manage them. The issue is not solved as custom stickers/emojis can't be created in SchildiChat, and one can't even use it as sticker.

~~Just checked, can't use emojis created from other clients with :shortcut:, I don't use markdown text editor.~~ Wrong account.

**Comment by SpiritCroc** [comment]
Of course some UI would be nice. There's already https://github.com/SchildiChat/SchildiChat-android/issues/186 to track that.

Also, it *is* possibly to send as sticker, see https://github.com/SchildiChat/SchildiChat-android/issues/186#issuecomment-1493254359.

> issue is not solved

Well, you complained in the issue about not being able to use these emotes and stickers at all, not about the lack of UI ;)

**Comment by bitokulo** [comment]
"Sticker/emojis **as** in Cinny". I state it lacks _as it works on Cinny_. Giving a feature which can't be accessed graphically isn't that much useful for the common person, is it?

**Comment by SpiritCroc** [comment]
"Sticker/emojis as in Cinny" could very well just refer to the technical side, just as you mentioned "a server's stickers", which would imply the technical aspect as well. Anyway, no need to argue, the issue https://github.com/SchildiChat/SchildiChat-android/issues/186 already exists?

**Comment by bitokulo** [comment]
Couldn't find it by searching 'custom emojis' tho

Yeah, you're right, if there's an issue about it, then it's fine :)

**Comment by SpiritCroc** [comment]
Hm right, it mentions emotes ([which seems to be the common way to call them rather than emojis](https://github.com/Sorunome/matrix-doc/blob/soru/emotes/proposals/2545-emotes.md)) in the description, but not the title. Added it to the title now too.
