### ISSUE TITLE
"Sorry, but managing extensions isn't supported on this device" message appear when trying to add widget integrations

### ISSUE THREAD

**Issue by suzdaleva** [SchildiChat/SchildiChat-android#198]
Hello, I have encountered the following behavior: when clicking on "Add Matrix apps" on the menu inside a chat room, error occurs with the message "Sorry, but managing extensions isn't supported on this device. We're working on it..."

1. Go to any chat room.
2. Click on a dot menu, select "Add Matrix apps".
3. See screen loading for a few seconds, then loading fails with the message "Sorry, but managing extensions isn't supported on this device. We're working on it...".

**Expected behavior**
App allows users to manage widget integrations. As far as I understand, there used to be a way to create a new widget with a link or edit/delete existing widgets.

**Screenshots**
![Screenshot_2023-07-04-13-02-06-469_de spiritcroc riotx debug](https://github.com/SchildiChat/SchildiChat-android/assets/82533889/0207a6bc-0a7c-4dfb-aac6-29ae445707d0)

**Smartphone:**
 - Device: Xiaomi M2004J19C
 - OS: Android 10.

**Additional context**
 - App version: 1.5.28.sc65
 - Matrix version: 1.5.30
 - Store: project imported from Github.
 - Homeserver: https://matrix.org/
 - Related labs settings: Integrations are enabled, Integration manager https://scalar.vector.im/

**Upstream relevance**
 - Does this issue exist in Element Android? - Yes.
 - Our team works on a custom widget that is supposed to be integrated in the app in the future. Thus widget integration is kind of a crucial feature for us. Could you, please, let me know whether this feature is currently disabled for all Android devices or is this just a case for some users? If it is globally disabled will it be restored any time soon?
Thank you!

**Comment by SpiritCroc** [comment]
I can reproduce. This looks to me like some web page returned by scalar.vector.im though, since it only shows up after accepting terms and conditions for scalar, and I can't find the strings from that message in the Android source code (so I guess it's not disabled form the Android side anyway). As this issue also happens for Element, better to ask them though, I won't touch that.
