### ISSUE TITLE
No passphrase option

### ISSUE THREAD

**Issue by Wandelstock** [SchildiChat/SchildiChat-android#2]
![Screenshot_20200809-110406.png](https://user-images.githubusercontent.com/58773587/89728779-20b15780-da30-11ea-94e3-40f2b76daf5d.png)

**Comment by SpiritCroc** [comment]
This screen is for setting up secure backup, which is used to backup your encryption keys. The passphrase is for logging into your account, and is not applicable here.

**Comment by Wandelstock** [comment]
In Riotx (last time i set the keys) there are 3 options, recovery key, passphrase key or file.

**Comment by SpiritCroc** [comment]
I don't see this option in Element either.

**Comment by Wandelstock** [comment]
Okay, i will look into that. Thanks!

**Comment by Wandelstock** [comment]
I did a clean install of Element and there are 2 options:
Recovery passphrase and recovery key.

Looks like this is an old bug in the security part. It was at the moment very hard to get devices trusted (Element 1.0.4 is still very buggy)

![Screenshot_20200809-122729.png](https://user-images.githubusercontent.com/58773587/89730433-beac1e80-da3e-11ea-92b1-74b8b1d8f875.png)
