### ISSUE TITLE
Voice Message Integration

### ISSUE THREAD

**Issue by maste9** [SchildiChat/SchildiChat-android#20]
SchildiChat is a big step towards the common messenger experience and towards being an alternative to xmpp-android-messengers like Conversations/PixArt.

As Voice Messaging obviously is an important feature for the common user an integration like in PixArt shouldn't be too complicated and will surely be widely appreciated.
As far as I can see they only impleted a way to record an mp3 and automatically prepare it for file transmission. On the receiving end such an attachment is automatically offered to be played.

Thanks for your work, I enjoy Schildichat a lot and it replaced element on my phone.

**Comment by SpiritCroc** [comment]
The upstream developers are planning to implement this: https://github.com/vector-im/element-android/issues/29
So once Element has it, I'll include it into Schildi too.

**Comment by SpiritCroc** [comment]
Included in v1.1.15!
