### ISSUE TITLE
Failing to render html messages

### ISSUE THREAD

**Issue by gaykitty** [SchildiChat/SchildiChat-android#201]
**Describe the bug**
Schildichat mobile is unable to render any message with format `org.matrix.custom.html`
**To Reproduce**
I am unsure what caused this to start happening. I don't think I updated to a new version today. I have not yet taken steps to fix the issue because I wanted to file a bug first.

**Expected behavior**
Messages are rendered

**Screenshots**
![Screenshot_20230729-185851](https://github.com/SchildiChat/SchildiChat-android/assets/126119280/9e07715f-e980-4a53-b905-1de42e95e4e6)

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: CalyxOS 4.11.0 (Android 13)

**Additional context**
 - App version: 1.6.3.sc69 [40101090] (F-22b5d7d6)
 - Store: F-Droid
 - Homeserver: the-apothecary.club
 - Related labs settings: None

**Upstream relevance**
 - Does this issue exist in Element Android? Unkown, don't use

**Comment by gaykitty** [comment]
After restarting the app multiple times the issue stop. Not sure why.

**Comment by SpiritCroc** [comment]
Can you send logs next time this happens?

**Comment by gaykitty** [comment]
> Can you send logs next time this happens?

It happened again, how do I do that? adb?

**Comment by SpiritCroc** [comment]
> It happened again, how do I do that? adb?

The easiest way would be using "bug report" from the option menu in the chat overview.

Logs over adb and sharing these manually would be possible as well, but unfortunately only if at least one of following criteria is fulfilled, as far as I'm aware:
- You have root access to your device
- You run a custom ROM which is not an `user` variant (so either `userdebug` or `eng`)
- The installed app is a DEBUG build (i.e., you compiled it yourself, since the builds I provide are not debug builds)

**Comment by gaykitty** [comment]
I'm getting "Bug report failed to send (failed with error timeout)"

**Comment by gaykitty** [comment]
Also FYI a friend of mine is also getting this bug.

**Comment by SpiritCroc** [comment]
Hm, looks like my server may be having issues again :/
Just had the same timeout when testing, on second and third attempt it worked though. I'm planning to move to a better vserver provider, but don't know when I'll have enough time to migrate everything, so best to try again and hope it goes through, sorry :|

**Comment by SpiritCroc** [comment]
Looks like I did receive the report though, will have a look when I have more time :)

**Comment by gaykitty** [comment]
Alright good. Best of luck in your log searching

**Comment by SpiritCroc** [comment]
Logs should be sufficient to fix that these messages do not show at all :+1: 
Not entirely sure what's happening there though, could happen that the "fix" I can think of right now will lead to formatted messages just falling back to unformatted text :thinking: 

Was there any particularly fancy formatting in these messages that you can think of?
Did all (or any?) of these messages that didn't render do special html formatting?

**Comment by SpiritCroc** [comment]
Oh, maybe it tells me more details if you "Enable verbose logs" in advanced settings, and after that, send another bug report next time it happens... :thinking:

**Comment by SpiritCroc** [comment]
Thank you for the logs! Once 1.6.5.sc71(or something newer) is out on F-Droid:
- If it happens again, please report again
- If formatted text doesn't render formatted, would be interesting to get another verbose log
