### ISSUE TITLE
Emojis with trailing newline cause app to crash

### ISSUE THREAD

**Issue by Black616Angel** [SchildiChat/SchildiChat-android#203]
**Describe the bug**
After writing an emoji, entering a newline in the same message sometimes makes the app crash

**To Reproduce**
1. Go to some chat
2. Enter the following text:
`test123🫥

`
3. Wait 1 second

**Expected behavior**
Crash

**Smartphone (please complete the following information):**
 - Device: Fairphone4
 - OS: Android 12

**Additional context**
 - App version: 1.6.3.sc69 [40101090] (F-22b5d7d6) 
 - Store: F-Droid
 - Homeserver: matrix-cyb.org
 - Related labs settings: none
 - Logs have been submitted using the app's built-in bug report (/"rageshake") mechanism: yes (Black616Angel@matrix-cyb.org) 

**Upstream relevance**
Does this issue exist in Element Android?
no

**Comment by SpiritCroc** [comment]
This appears to be a bug related to "rich text editor" which we do not touch, can you try without it?

**Comment by Black616Angel** [comment]
Seems like it. I tried without and it didn't crash. In element I had this not enabled. And now after trying it in element, that doesn't crash but randomly deletes the text...
