### ISSUE TITLE
Crash & rendering issues during matrix.org downtime

### ISSUE THREAD

**Issue by solonovamax** [SchildiChat/SchildiChat-android#206]
**Describe the bug**
There were issues with rendering markup, followed by a crash. This happened while the matrix.org servers were down/unresponsive.
I submitted a crash report at around 10:28, EST. My account is `@solonovamax:matrix.org`.

**To Reproduce**
Unsure how to reproduce. This happened during the matrix.org outage at around 10:20 EST.

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: OnePlus 9 Pro 5G
 - OS: OxygenOS 13.1

**Additional context**
 - App version: `1.6.5.sc71 [40101212] (F-b98153c4)`
 - Store: F-Droid
 - Homeserver: matrix.org
 - Related labs settings:
   - I have the following labs enabled:
     - Open at first unread
     - Only mark chats as read if fully read
     - URL previews in encrypted chats
     - Mark chats as unread
     - Swipe chat list to switch space
     - Open without reading
     - Enable swipe to reply in timeline
     - Enable LaTeX mathematics
     - Enable threaded messages
     - Enable live location sharing
     - Enable new layout
     - Enable deferred dms
     - Enable new session manager
     - Enable client info recording
 - [x] Logs have been submitted using the app's built-in bug report (/"rageshake") mechanism

**Upstream relevance**
 - Does this issue exist in Element Android? Unsure. Unable to reproduce. But, it most likely does.
 - If this issue exists in Element Android, please also link the corresponding bug report (create a new one if it doesn't exist yet)

**Comment by solonovamax** [comment]
Update: I can now reliably reproduce in a specific room. it is most likely one of two messages.
I will look into it further in a few hours and see if I can narrow down the exact cause of it.

Element displays the following message when it occurs
> Element encountered an issue when rendering content of event with id '[omitted]'

and then does not render the content of the message at all. Schildi must have a fallback to show the raw message contents if it cannot be rendered properly.
The labs I have enabled on Element are:
- Swipe to reply in timeline
- Enable threaded messages
- Enable live location sharing
- Enable new layout
- Enable deferred dms
- Enable new session manager
- Enable client info recording

I will upstream this issue later, once I have narrowed down the cause.

**Comment by SpiritCroc** [comment]
In Element, can you enable developer options and long press the message, then "view source" and copy what it shows there to paste here?

**Comment by solonovamax** [comment]
> In Element, can you enable developer options and long press the message, then "view source" and copy what it shows there to paste here?

I will narrow down exactly which part of the message is causing it later, and then send conteny that can reproduce it. If I cannot narrow it down, I will provide the original message/a link to the channel. However, I'd prefer if I can keep the message contents private if possible. But, I am willing to share if it is needed.

**Comment by SpiritCroc** [comment]
Yes of course, if you can narrow it down even better :+1:

**Comment by solonovamax** [comment]
I cannot for the life of me figure out how to reproduce it in a clean environment, so I cannot narrow it down.

Logs give no information as to what is happening, either. And, I'm having issues with compiling SC so I can't debug it in my IDE.

Would you like me to invite you to the room it occurred in? (I'll invite you directly, or invite any other users upon request, I don't want to give a public invite link, however, just to avoid spam)

**Comment by solonovamax** [comment]
I just realized I never attached the screenshot of the issue.

Here is that:
![Screenshot_2023-08-20_10-06-50](https://github.com/SchildiChat/SchildiChat-android/assets/46940694/43f859b8-368c-4720-8372-1a068094fa20)

**Comment by SpiritCroc** [comment]
Ah, I thought it crashed?

If you're willing to invite me and in case I get the same issue, that of course could help. Note that I'll be in vacation now for 3 weeks, so I haven't even looked at the logs yet - if you want, I can also try finding the issue based on logs first only before you invite me. But you probably won't hear from me for the next 3 weeks anyway.

In case you invite me, please use `@spiritcroc:matrix.org` (don't want to join random rooms with my own homeserver)

**Comment by solonovamax** [comment]
I cannot reproduce the crash, however the rendering issues can be reproduced.
I'll send an invite rn
