### ISSUE TITLE
[Feature request] Variable playback speed of voice message

### ISSUE THREAD

**Issue by Duvio** [SchildiChat/SchildiChat-android#209]
**Is your feature request related to a problem? Please describe.**
People sending long voice messages.

**Describe the solution you'd like**
Add ability to listen to voice messages on higher playback speeds.

**Additional context**
WhatsApp for example already supports this. There is a button right next to the voice message where you can set the playback speed to 1x, 1.5x and 2x.

**Comment by SpiritCroc** [comment]
Duplicate of https://github.com/SchildiChat/SchildiChat-android/issues/109.
