### ISSUE TITLE
Libwebp 0day

### ISSUE THREAD

**Issue by linsui** [SchildiChat/SchildiChat-android#210]
**Describe the bug**
SchildiChat-android uses https://github.com/zjupure/GlideWebpDecoder which uses libwebp 1.2.4. We can patch the lib by replacing https://github.com/zjupure/GlideWebpDecoder/tree/master/webp_decoder/src/main/jni/libwebp with https://github.com/webmproject/libwebp/commits/1.2.4.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung S6]
 - OS: [e.g. Android 6.0]

**Additional context**
 - App version: [Look it up in Settings / Help & About. Click "Version" there to copy it. "Latest version" is not a valid version!]
 - Store: [e.g. F-Droid, Google Play, SpiritCroc's F-Droid]
 - Homeserver: [e.g. matrix.org]
 - Related labs settings: [Have you enabled any settings in labs (which ones), and does the issue still exist when disabling these?]
 - Logs have been submitted using the app's built-in bug report (/"rageshake") mechanism: [yes/no]

**Upstream relevance**
 - Does this issue exist in Element Android?
 - If this issue exists in Element Android, please also link the corresponding bug report (create a new one if it doesn't exist yet)

**Comment by licaon-kter** [comment]
ref: https://blog.isosceles.com/the-webp-0day/

**Comment by SpiritCroc** [comment]
Oh, thanks for pointing out, I'll try to get a release out tomorrow

**Comment by SpiritCroc** [comment]
> We can patch the lib by replacing https://github.com/zjupure/GlideWebpDecoder/tree/master/webp_decoder/src/main/jni/libwebp with https://github.com/webmproject/libwebp/commits/1.2.4.

Is there a straightforward approach to do this without forking GlideWebpDecoder? If not, I can probably just kick that library out, the amount of additional media that the library enables us to view is rather small and shouldn't justify maintaining it if it becomes too annoying

**Comment by linsui** [comment]
I thought not. You can add it back when the lib is updated.

**Comment by SpiritCroc** [comment]
Addressed in v1.6.5.sc72 (for test builds: v1.6.5.sc72-test4).

**Comment by licaon-kter** [comment]
fyi https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13782/diffs

**Comment by linsui** [comment]
GlideWebpDecoder released a new version with the updated libwebp so if you want you can add it back.
