### ISSUE TITLE
Child mode

### ISSUE THREAD

**Issue by iiitomo** [SchildiChat/SchildiChat-android#22]
**Context**
I want to allow my child communicate (text/audio/video) with his family via SchildiChat (on a phone with no SIM and firewall allowing internet access only to SchildiChat).  I have created for him a dedicated SchildiChat account in which I have created DirectMessages conversations with only trusty contacts.
Now I want to be sure he doesn't contact (nor be contacted by) anyone else than those trusty contacts.

**Solution I'd like**
I'd like to find in the Settings a possibility to block features that are unwanted for a child usage: block sending/accepting Invites, block access to Rooms, block addition/removal of Rooms/DirectMessages, block join/quit. 
Unlocking this should require to type the account password.
This feature could be called 'Child mode'.

**Alternative solution if requesting a password is too hard to implement**
For a 1st implementation, it would be fine for me if no password was requested. If the toggle for the 'Child mode' is in the 'Advanced Settings' or the 'Security & Privacy' settings, I don't think my child would find it and unlock it... until he becomes smart enough :)

Thanks for reading, and keep up the good work !

**Comment by SpiritCroc** [comment]
Hi, thanks for your suggestions, that's some interesting use-case.
Due to lack of time, I probably won't work on it anytime soon (but I'm open to contributions).

Have you considered setting up a homeserver that doesn't federate? If you have a server that cannot talk to other servers, users are also restricted to chat only with users on this server - maybe this might be enough to avoid chats with untrusted contacts for you. By disabling the user directory, you can also avoid that users find each other if they don't know the id of the other.

**Comment by iiitomo** [comment]
hi Croc, thanks for the suggestions.
Isolated homeserver would be safe, but I don't have skills nor hardware to set up, and also i guess it would prevent trusted contacts to use Matrix outside this restricted circle, which I don't want to impose them.
By 'disabling user directory', do you mean the 'identity server' in the Settings ? I observe that by default it's emtpy (setting says 'You are not using any Identity Server') and nevertheless my child can be found by anyone (I checked via another account), and my child can see list of unknown people when create a new chat.

**Comment by SpiritCroc** [comment]
Yes, the downside of that approach would be that nobody can talk to other servers.
Disabling user directory would be a server setting, which controls if you can see other users on the same server, even when not knowing their id, which works independently of the identity server, which maps users to phone numbers/emails/....

**Comment by iiitomo** [comment]
ok, so not something I can do then.

I just updated my original post, please check the **Alternative solution** section.
