### ISSUE TITLE
Can we add a gif picker that works on desktop?

### ISSUE THREAD

**Issue by jreiners** [SchildiChat/SchildiChat-android#227]
**Is your feature request related to a problem? Please describe.**
I'd love to see GIFs better supported on desktop

**Describe the solution you'd like**
I'd love a Gif picker added to the interface, to allow easier meming, rocketchat, our old chat had gifs that would auto insert but I just cant get it working on the desktop, mobile messages sent using the gif picker of gboard embed and play back fine, where gif links pasted into rooms do not animate.

**Describe alternatives you've considered**
I've tried pasting different gif links in on desktop but they never play correctly.

**Additional context**

**Comment by jreiners** [comment]
I'm just thinking it'd be great for coworkers that want to join in on the action over matrix, thats my only internal user complaint at the moment.

**Comment by SpiritCroc** [comment]
So this is something desktop would need to implement? 
Then it should go to https://github.com/SchildiChat/schildichat-desktop, this repo is for Android.

**Comment by jreiners** [comment]
Oh sorry my bad, will do
