### ISSUE TITLE
Changelog in the tag comment

### ISSUE THREAD

**Issue by opk12** [SchildiChat/SchildiChat-android#228]
**Is your feature request related to a problem? Please describe.**
The [tag commit messages](https://github.com/SchildiChat/SchildiChat-android/tags) do not tell where to find the changelog. Apparently it is hidden under [`sc/fastlane/metadata/android/en-US/changelogs`](https://github.com/SchildiChat/SchildiChat-android/tree/sc/fastlane/metadata/android/en-US/changelogs).

**Describe the solution you'd like**
If I open the page for a tag ([example](https://github.com/SchildiChat/SchildiChat-android/releases/tag/sc_v1.6.10.sc75)), it shows the changelog or links the relevant GitHub page.

**Comment by SpiritCroc** [comment]
I guess I could change my tooling to do `git tag -m` (or `-F`) with the commit message and hope that will be displayed in github. Maybe I'll experiment with that for future releases, but it's too late to touch old releases, since I don't like re-pushing all the tags.

**Comment by opk12** [comment]
Thank you for looking into it. I agree that old releases are not worth the effort.

**Comment by SpiritCroc** [comment]
Will probably be fixed with https://github.com/SchildiChat/SchildiChat-android/commit/f05af3f8b30069fce9fea1de4b11f8ccec98e0bb - but I guess we'll need to wait for the next release to be sure
