### ISSUE TITLE
Simplified mode which hides public room functionality

### ISSUE THREAD

**Issue by iiitomo** [SchildiChat/SchildiChat-android#23]
Edit by SpiritCroc:

A simplified mode (-> setting) with reduced functionality, hopefully improving accessibility for 'non-tech' users, with following changes:
- Hide public room functionality (rationale: people chatting with strangers on the internet can be considered advanced users)
    - Clicking on + / Rooms goes directly to "Create new room" instead of the intermediate step which allows joining public rooms
    - The "New room" screen would hide the setting to make the room public and publish it in the room directory
    - Hide room address settings in the room settings
- Hide encryption settings (rationale: encryption is hard to explain to users without background knowledge)
    -> Always encrypt by default when creating a new room (like Element does)
- Possibly add a prompt after first login whether to use simple or advanced mode, or maybe also show once in retrospective for existing users (rationale: optimally, 'non-tech' users do not need to configure any settings, which might be challenging, but we probably have a significant amount of users who would miss public room joining if we hide it by default)
    - Possible descriptions:
        - "I only plan to chat with people I know"
        - "I'm looking for full functionality, including the possibility to join public rooms"

### Original issue

**Context**
Users in my family only use the Direct Messages, and don't use the Rooms, so would like to hide all features related to Rooms.

**Solution I'd like**
In Settings, I'd like to find a 'Hide Rooms' option (toggle) that removes all Room features.
(maybe this should be possible only if user hasn't joined any Room)

Thanks for your great work!

**Comment by SpiritCroc** [comment]
This doesn't sound too useful to me. At the protocol level, direct chats and rooms are currently the same thing except for one flag that tells if a chat is direct or not. You can also create multiple "direct" chats with the same user, and invite other users into "direct" chats.

**Comment by iiitomo** [comment]
Hi SpiritCroc, I agree but non-tech users don't know that. 
So I'll try to reformulate :-)
The purpose here is to make Schildi more attractive for 'non-tech' people, e.g. coming from Whatsapp/Facebook Messenger and similar. These don't use/need public rooms (at least by default), and are uncomfortable with the 'Direct messages'/'Rooms' double-choice of the (+) button.

My first (and preferred) proposal is to show a very simplified UI by default: a simple (+) button that goes directly to the 'Direct messages' menu. But with possibility for intermediary/advanced users, via Settings (or top-right menu for easier access) to 'Enable public rooms' that would switch to the (+) button with double-choice.

Alternatively (I like this one too), you could propose to user: 'Do you want a simple interface without Public Rooms? (public rooms can be enabled later on)' in the start screens just after install. This would trigger start choice between (+) button with Simple or Double-choice.

And worst case, please just add in Settings the possibility to switch to simple (+) button, I will use it when I install/show Schildi on the phone of my 'non-tech' contacts.

What do you think ?

**Comment by SpiritCroc** [comment]
From how I understood your initial suggestion, I thought you wanted to hide all kinds of group chats, including private groups, which is a common use-case for most users - the only messengers that do not feature this natively that come to my mind right now would be SMS and E-Mail probably. Whatsapp definitely allows for group chats; I don't know about Facebook, which I never used.

Now after reading your reformulation, it makes more sense to me: the keyword is "public" rooms. So to check if I understood it correctly now what such a setting would do:
- Clicking on + / Rooms goes directly to "Create new room" instead of the intermediate step which allows joining public rooms
- The "New room" screen would hide the setting to make the room public and publish it in the room directory
- Hide room address settings in the room settings

Is this what you want? Is there any other public room functionality that should be affected?

**Comment by iiitomo** [comment]
Yes, very good idea!  I think you understood my point now :-)
Please also hide the setting to disable encryption, in my opinion the private rooms should always be encrypted.

**Comment by SpiritCroc** [comment]
Good idea, I updated the issue with my current thoughts on the topic, so I can remember them faster when I find time to look into this.
