### ISSUE TITLE
Biometric stays up

### ISSUE THREAD

**Issue by ByteBitten** [SchildiChat/SchildiChat-android#24]
SchildiChat 1.0.10.sc.25 via F-Droid
Nokia 8 Android 9 with fingerprint-unlock enabled
Fingerprint enabled (Settings>Security&Privacy>Protect access) with pin.

**Reproducing:**
- enable fingerprint and pin
- open SchildiChat
- lock phone
- unlock phone

**Issue:**
The fingerprint scan pop-up stays up after unlocking phone with SchildiChat open.
I can't click home. I had to reboot my phone.

**Possible cause:**
Nokia 8 has home button as the fingerprint scanner.
Possibly not 'clicking' home but fingerprinting and visa versa.

**Screenshot:**
![Screenshot_20201114-131850](https://user-images.githubusercontent.com/3299710/99147215-850f3300-267f-11eb-8115-129fdc892db8.png)

**Comment by SpiritCroc** [comment]
Does the "use pin" button work? Does clicking outside of the "Sign in" popup hide it?

**Comment by ByteBitten** [comment]
I will let you know once I reproduce it. Doesn't always happen.
For what I remember, I pressed all buttons (also back and home).
The pop-up prevents screen interaction completely. (no notification-bar pullable).
