### ISSUE TITLE
Start minimized

### ISSUE THREAD

**Issue by voidzero** [SchildiChat/SchildiChat-android#242]
Couldn't find this anywhere - how can I start up Schildichat minimized/just into the tray? I'd like it to start that way after logging into my Linux environment... thanks.

**Comment by SpiritCroc** [comment]
This repo is for the Android app and not the desktop app, you can find issues for desktop [here](https://github.com/SchildiChat/schildichat-desktop/issues).
However, when you launch schildichat-desktop, you can pass it `--hidden` so it starts just in tray.

**Comment by voidzero** [comment]
> This repo is for the Android app and not the desktop app, you can find issues for desktop [here](https://github.com/SchildiChat/schildichat-desktop/issues). However, when you launch schildichat-desktop, you can pass it `--hidden` so it starts just in tray.

 Oops! It was a bit late at night, sorry, and thank you. 😄
