### ISSUE TITLE
Pictures and videos black / missing

### ISSUE THREAD

**Issue by fakeacc4** [SchildiChat/SchildiChat-android#245]
**Describe the bug**
Send and received Pictures and videos are only black on mobile.
Trying to download pictures/videos reports network error.
On browser login on windows everything it is visible and works 
Text messages are working fine

**To Reproduce**
Select picture 
Share
Waiting for upload
Picture is visible for sender 

**Expected behavior**
See the picture and be able to download it.

**Smartphone (please complete the following information):**
Several schildichat on mobile users with motorola, oneplus, Nokia

**Additional context**
 - App version:1.6.18.sc
 - Store: F-Droid & Google Play
 - Homeserver: tchncs.de
 - Related labs settings: none

How to create Logs?

We have multiple groups with several schildichat users and some fluffychat users on IOS. Error only happes on Android devices since one or two weeks. First only ocassionally, now everytime. No media is visible. 

![Screenshot_20240725-234215_SchildiChat_1](https://github.com/user-attachments/assets/8ad24bf4-2e07-4ea1-aa70-89fa246165ac)

Edit: 29.07.
I did try a couple things that didn't work. 
Got my old phone with version 1.6.12 sc77 and have the same problem
Former visible pictures/videos are black after logging out or trying initial synchronisation and are no longer visible
Sending pictures with schildichat(f) to schidichat(fdroid) doesn't show them aswell in the fdroid version. On [f] there are still visible from a new created one account. Maybe there is a server problem, because i got a new account on a different home matrix server? 
Trying some backup key recoverys and that didn't work aswell.

**Comment by cy8aer** [comment]
It looks like the backend has authenticated media switched on. I have the same effect when switching it on on my synapse instance.

**Comment by cy8aer** [comment]
according to https://github.com/element-hq/element-android/issues/8888 authenticated media is missing in element 1.6.18

**Comment by SpiritCroc** [comment]
I see, makes sense for authenticated media. I published [1.6.20.sc80](https://github.com/SchildiChat/SchildiChat-android/releases/tag/sc_v1.6.20.sc80) last week so I guess it'll start working once you update. It's already available in the [release channels](https://schildi.chat/android/) I control.
