### ISSUE TITLE
Push notification broken

### ISSUE THREAD

**Issue by Manifoldme** [SchildiChat/SchildiChat-android#248]
**Describe the bug**

Push notification is broken, I don't receive notification until the app is manually opened.

**Screenshots**
![Screenshot_20240904_165417_SchildiChat](https://github.com/user-attachments/assets/4a1c2cba-7d0f-4cd3-93e3-21e062373f85)

**Smartphone (please complete the following information):**
 - Device: Samsung S21 Ultra
 - Device: Samsung S23 Ultra
 - OS: Android 14, One UI 6.1, Security patch August

**Additional context**
 
1.6.20.sc80 [40101300] (G-79578a32)
Self-hosted server with federation of.

It might be a Samsung thing, I had this problem many years ago on S21U, my girlfriend had it on S23U a year ago,
Schildi works for few weeks, and than, as you can see, it's not. We moved to Element, now I'm back and this problem isn't solved.
Battery - Unrestricted
All kind of notifications are allowed.
Element works fine.

**Upstream relevance**
 - Does this issue exist in Element Android?
 
No, Element notification works without any issue.

**Comment by RoastPotatoes** [comment]
I'm also having this issue

Poco F3 Android 14 1.6.20.sc80 from play store

**Comment by wapsi** [comment]
I'm also having this issue (Samsung Z Fold 5, Android 14).

First I thought it was the latest Samsung Android update that borked this and I tried all the battery/sleep related settings, but they were correctly set and the push notifications have worked earlier just fine. And there is not any issue with push notifications of all other apps, so my guess is that it's related to SchildiChat itself.

Update: The same 502 push notification error happens on my Lenovo tablet (Android 14) also, so it's not Samsung related issue only.

**Comment by pat-gal** [comment]
Same problem here, I noticed it yesterday, with several users of our self-hosted instance also affected.
I ran the notification troubleshooting tool as well, and also got an HTTP 502 error every time at the Test Push step.

Running Schildi version 1.6.20.sc80 [40101300] (G-79578a32)

**Comment by BloodyIron** [comment]
Yeah me and my SO are having push notification issues on Android too. Unsure exactly when it started but probably in the last few weeks. What's going on?

**Comment by BloodyIron** [comment]
Er, well... the failure is inconsistent it seems... sometimes works, sometimes doesn't, but the change seems to be recent.

**Comment by EmnichtdaYT** [comment]
same here :) I have corresponding synapse server logs here
`WARNING - httppush.process-137 - Failed to push data to @[redacted]/de.spiritcroc.riotx/[redacted]: <class 'synapse.api.errors.HttpResponseException'> 502: Bad Gateway`

**Comment by 4censord** [comment]
works fine on my google-less phone. So its something with googles push stuff?

**Comment by Trogvars** [comment]
Same error on several devices like Poco X3 and Samsung Galaxy S23.
But works on Poco M3.

**Comment by SpiritCroc** [comment]
Sorry, we somehow missed some server-side FCM API deprecation, we're on it.

**Comment by Trogvars** [comment]
Here is a part of log file on Synapse-Matrix server:
111_11_11111_111111_11_11111_111_1_1 HTTP/1.0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.11.76 Chrome/126.0.6478.185 Electron/31.3.1 Safari/537.36" [0 dbevts]
2024-09-06 09:22:58,190 - synapse.push.httppusher - 236 - INFO - httppush.process-89 - Processing 1 unprocessed push actions for @xxx:xxx.xxxx.com/de.spiritcroc.riotx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx starting at stream_ordering 57408
2024-09-06 09:22:58,365 - synapse.http.client - 428 - INFO - httppush.process-89 - Received response to POST https://sygnal.schildi.chat/_matrix/push/v1/notify: 502
2024-09-06 09:22:58,366 - synapse.push.httppusher - 416 - WARNING - httppush.process-89 - Failed to push data to @xxx:xxx.xxxx.com/de.spiritcroc.riotx/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: <class 'synapse.api.errors.HttpResponseException'> 502: Bad Gateway
2024-09-06 09:22:58,366 - synapse.push.httppusher - 315 - INFO - httppush.process-89 - Push failed: delaying for 128s

**Comment by Trogvars** [comment]
Yeah! It's working now!

**Comment by Trogvars** [comment]
Seems like error is gone. Everything is ok now.

**Comment by wapsi** [comment]
I can confirm this as well. Push notifications are working again. Thanks a lot for the very quick response, keep up the good work! :)

**Comment by SpiritCroc** [comment]
Great to hear! It seems like our server may still be a bit stressed with catching up with previously missed notifications, let's hope it'll be fully up to speed again soon

**Comment by BloodyIron** [comment]
> Sorry, we somehow missed some server-side FCM API deprecation, we're on it.

How exactly does this overlap with 100% self-hosted environments? Are they only really 95% self-hosted?

**Comment by 4censord** [comment]
>> Sorry, we somehow missed some server-side FCM API deprecation, we're on it.

> How exactly does this overlap with 100% self-hosted environments? Are they only really 95% self-hosted?

Because of how Google does Android, its very hard to have push notifications without them going via googles firebase. Its possible, by haveing either the app do extra work, or by hosting a push service yourself (e.g. ntfy). Most people dont do that, so push still requires these google services

**Comment by SpiritCroc** [comment]
> How exactly does this overlap with 100% self-hosted environments? Are they only really 95% self-hosted?

If you install the version from the Play Store on a device having Play services, the app will by default use Google's FCM services to push notifications (better for the battery to have all notifications for all apps from one server only, and least effort to get running for most users who do not care about de-googling). Since FCM only allows apps to receive pushes signed by their own developer, and thus not an arbitrary homeserver of your choice, we need to operate a proxy such that your homeserver can indirectly notify SchildiChat about new notifications, in order to wake the app and query the actual missing messages.

If you want a 100% self-hosted environment, you will also need to self-host some unified-push compatible server (e.g. ntfy) and configure it on your device (first in the ntfy app to use your server, then in SchildiChat to use ntfy).

Further reading on unifiedpush at https://unifiedpush.org/

**Comment by BloodyIron** [comment]
Thanks to you both @SpiritCroc and @4censord for clarifying on that! :) Much appreciated.

**Comment by su-ex** [comment]
Push notifications via FCM should now work again for both (next and legacy) apps.

**Comment by BloodyIron** [comment]
Yay thanks @su-ex !

**Comment by BloodyIron** [comment]
Not sure if it's related to the push changes, but Android Schildi seems to be unreliable for receiving messages on one of my friends' devices and this is a new thing in the last few weeks maybe. We're using public matrix servers, not self-hosted, so unsure if there's any recent changes somewhere in the ecosystem that could be overlapping here. Is there any possibility this push change could be related to the problem?
