### ISSUE TITLE
Markdown is not observed

### ISSUE THREAD

**Issue by monochromec** [SchildiChat/SchildiChat-android#257]
**Describe the bug**
The mobile version does not observe markdown.

**To Reproduce**
1. Create a message with markdown (ie., '_' for italics, backticks for code, etc.)
2. Save message
3. The markdown is saved "as is" with no impact on the formatting of the message text

**Expected behavior**
Markdown formatting is applied similar to the desktop versions.

**Smartphone (please complete the following information):**
 - Device: FP4
 - OS: Stock Android 13

**Additional context**
 - App version: 1.6.24c83
 - Store: Playstore
 - Homeserver: N/A
 - Logs have been submitted using the app's built-in bug report (/"rageshake") mechanism: no

More info can be supplied if required.

**Comment by SpiritCroc** [comment]
Have you enabled "Markdown formatting" in Settings / Preferences?

**Comment by monochromec** [comment]
That solved the issue.

Thanks for the hint. Closing this.
