### ISSUE TITLE
Unread messages tab

### ISSUE THREAD

**Issue by SpiritCroc** [SchildiChat/SchildiChat-android#27]
For non-combined chat lists, we currently have the (lab)-option to add a tab for notifications. This might also be helpful for long chat lists when using the combined chat list, so my suggestion is the following:
- Allow enabling the notifications tab also when having a combined chat list
- Think about whether we want to show the unread counter badge in the tab icon in this scenario, as it would be the same for both tabs
- Add a setting to also show chats with unread messages in there, instead of only those with actual notifications

**Comment by ShadowJonathan** [comment]
Maybe make this a "catagory"? Similar to favorites and normal/low priority, and make it possible for users to put this category above or below favorites in their menu

**Comment by SpiritCroc** [comment]
> Maybe make this a "catagory"? Similar to favorites and normal/low priority, and make it possible for users to put this category above or below favorites in their menu

Not sure if it's a good idea to move chats out of their user-defined category for that matter. Users use the priority categories to rate the importance of chats (and thus show higher importance chats above lower priority), and a new category for unread chats would ignore this and mix all chats together solely by timestamps instead.
Furthermore, having an unread category *below* favorites makes no sense to me, since this would move unread favorites further down instead of up.
