### ISSUE TITLE
No sound on notification arrivals.

### ISSUE THREAD

**Issue by nconde77** [SchildiChat/SchildiChat-android#29]
**Describe the bug**
Schildi does not play any sound when notifications arrive. I have enabled them in the Android preferences and in the app setup, to no avail.

**To Reproduce**

1. Go to 'Settings'
2. Click on 'Notifications'
3. Click on 'Notification sounds'
4. Scroll down through Notifications sounds
5. Selec any one (I chose 'Sapo' in Spanish). It plays Ok.
6. Go back with the upper arrows to the main screen and wait for a message to arrive.
   When it does, no sound is played.

**Expected behavior**
A sound should play on message arrival, but no sound comes out.

**Screenshots**
N/A.

**Smartphone (please complete the following information):**
 - Device: Xiami Redmi Note 3 Pro.
 - OS: Android 6.0.1, MIUI Global 10.2.1.0.

**Additional context**
 - App version and store: 1.0.10 from F-Droid.
 - Homeserver: matrix.org.
 - Notifications are enabled for both the account and session.

**Upstream relevance**
 - Does this issue exist in Element Android?
     Yes, it does.

**Comment by SpiritCroc** [comment]
Related upstream issue for reference: https://github.com/vector-im/element-android/issues/1344
