### ISSUE TITLE
Strange behaviour icons sc dark and sc black mode

### ISSUE THREAD

**Issue by Wandelstock** [SchildiChat/SchildiChat-android#4]
On Android 6 version sc11

![Screenshot_20200811-221148.png](https://user-images.githubusercontent.com/58773587/89944370-fcb46880-dc1f-11ea-9fad-e6fab2a32b9e.png)

On android 9 is no problem

**Comment by Wandelstock** [comment]
Btw same problem at standard dark and black mode. And this error is also in Element itself.

**Comment by SpiritCroc** [comment]
Thanks for reporting! Since I changed the icons for Android versions > 7.0, I guess it makes sense to change it for previous versions as well (and fix this issue while doing so).
