### ISSUE TITLE
I can't send messages after rotate my phone to landscape mode

### ISSUE THREAD

**Issue by adriaaah** [SchildiChat/SchildiChat-android#44]
**Describe the bug**
 When I'm chatting, if I turn my phone to landscape mode, I can't send any more messages until I get back to the room list.

**To Reproduce**

1. Go to a room in portrait or landscape mode.
2. Write a message or not.
3. If you are in portrait mode, turn the phone to landscape mode.
4. Expand the message or type one.
5. Click Done button.
6. Hide keyboard.
7. Click send button.
8. Message is not sent.
9. Turn the phone to portrait mode.
10. The part of the message written in landscape mode was erased.
11. Click to send button.
12. Message is not sent.
13. Delete the message and write a new one.
14. Click send button.
15. Message is not sent.
16. Return to the room list.
17. Go to the room again.
18. Click send button.
19. Message sent.

**Expected behavior**
 Send message in landscape mode and portrait mode.

**Smartphone (please complete the following information):**

- Android-Version: 6.0.1
- Device: A0001
- OS Version: 3.4.110-cyanogenmod-ge6be560(3c3f0aca9b)
- OS API Level: 23
- Manufacturer: OnePlus
- Model (and Product): A0001 (bacon)

**Additional context**
 - App version: 1.0.14.sc27 from F-Droid
 - Homeserver: matrix.debian.social

**Upstream relevance**
 - Does this issue exist in Element Android?
https://github.com/vector-im/element-android/issues/2742

**Comment by SpiritCroc** [comment]
Note to self: sounds like maybe the click listener gets lost upon orientation change.

However, I was not able to reproduce this on my device (Android 11) - maybe I need to recheck with an older Android version.
Further note: when I click done button in landscape mode, it already sends the message. It does not make any difference if I close the keyboard first and use the app's send button instead, it still works without problems for me. I'm also on version 1.0.14.sc27.

**Comment by SpiritCroc** [comment]
Seems fixed upstream
