### ISSUE TITLE
Can't connect to servers on the same lan

### ISSUE THREAD

**Issue by mariorossi77** [SchildiChat/SchildiChat-android#46]
Steps to reproduce the behaviour:
1. start matrix-synapse on 192.168.1.1
2. start schildi on 192.168.1.2
3. connect to the server

error message:
no network. please check you internet connection 

there is internet connection and the server works if i connect from any desktop client
if i open `http://192.168.1.1:8008` in the phone browser i see the "it works" page.
edit: it seems that it just wont accept any non https address

**Comment by SpiritCroc** [comment]
Upstream issue: https://github.com/vector-im/element-android/issues/2420
Doesn't sound like a big issue to me, since you should not be using plain http in a production setup.

**Comment by mariorossi77** [comment]
matrix-synapse runs on http by default, if the instance is not federated you can use a vpn to access it and there is no need for a tls certificate. At least the desktop clients work with http.
closing this since no one is interested in this issue albeit creatin much hassle to many users who dont need https. 

https://github.com/vector-im/element-android/issues/1793
