### ISSUE TITLE
Add option to have rounded chat bubbles

### ISSUE THREAD

**Issue by alvierahman90** [SchildiChat/SchildiChat-android#48]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I much prefer having bubbles so thank you for making this fork! However,I think it would be must nicer aesthetically to have rounded chat bubbles rather than the boxy ones currently in the app, like the ones you get in Telegram:

![image](https://user-images.githubusercontent.com/23002610/113049330-6a0b0e80-919b-11eb-8d9b-22a0258aa58d.png)

**Describe alternatives you've considered**
None.

**Comment by alvierahman90** [comment]
I have wee bit of experience with android app development but I have no idea where I'd start making this a reality so if you could point me in the right direction I would be happy to have a crack at this myself and make a PR :)

**Comment by SpiritCroc** [comment]
The current shapes are based on those from the AOSP messenger app and can be found by searching for `.9.png` files that start with `msg_bubble` in the drawable directories.
For configurable chat bubbles (no, I won't make more rounded bubbles the default), a starting point would be recreating these bubbles in xml, so we have one file per shape for all screen densities, and so the corner roundness can be easily changed. Once we have multiple values for these, one will probably also need to adapt the message content padding for each corner setting. You can grep the code for the usage of these drawables to find the appropriate locations.

**Comment by SpiritCroc** [comment]
I've been doing some changes recently to add a setting for more bubble appearances. But I can't really tell what people who prefer more rounded bubbles would like, so feedback wanted:

![Screenshot_20220303-101445_SchildiChat_dbg](https://user-images.githubusercontent.com/12481742/156535502-87afc237-0599-4107-9645-361a93da0940.png)

Is this fine? Or should it be slightly less round? Should we remove the bubble tail here? Do we need options for users to chose between the just mentioned aspects?

**Comment by rottenwheel** [comment]
@SpiritCroc I think those WIP rounded bubbles look fine, though perhaps a less rounded shape might look even better for some others. Not sure what bubble tail is. As per usual, it would be rather difficult to please all users; therefore, adding options to make them less or more rounded might not be a bad idea should this feature be added to SchildiChat Android. Thanks for your great work.

**Comment by SpiritCroc** [comment]
Ah, the tail is the thing pointing to the avatar :)
Current default bubble style uses roundness of 3 pixels, and above screenshot 12 pixels. I can imagine adding one with 8px for example as well

**Comment by pioneer** [comment]
This is absolutely fine for me, really like more rounded like on the screenshot above. I personally don't like the tail, but even more I prefer configurability for:
- bubble corner radius
- whether to show or not the tail

**Comment by SpiritCroc** [comment]
Due to implementation restrictions, freely choosing the radius won't be an option, but rather a list of pre-selected values can be provided. If you wish for any value in particular, please tell me :) 
Reminder, current implementation uses 3px, above screenshot 12px.

**Comment by pioneer** [comment]
Particularly for me please keep 12px in the list, much thanks!

**Comment by hughwilliams94** [comment]
These look great! I wonder whether it might be possible to add some rounding to the tip of the tail and the point where the tail joins the bubble in a way similar to the telegram bubbles shown in OP?

**Comment by SpiritCroc** [comment]
> These look great! I wonder whether it might be possible to add some rounding to the tip of the tail and the point where the tail joins the bubble in a way similar to the telegram bubbles shown in OP?

Possible if somebody writes the vector path for that, compare the current tail here: https://github.com/SchildiChat/SchildiChat-android/blob/sc/vector/src/main/res/drawable/msg_godbubble.xml#L81-L85
(Handwritten path would be preferred over something that inkscape spits out, so paths don't get more complex than necessary)

**Comment by hughwilliams94** [comment]
I'll try and take a look at editing the path if I can get around to it

**Comment by pioneer** [comment]
This may be less related to the roundness of bubbles, but IMO worth noting that in every other messenger I can remember, the name of the user is displayed with a smaller font than the text inside the bubble. It could add a little more aesthetic.

**Comment by hughwilliams94** [comment]
@pioneer that should be discussed in a separate issue
