### ISSUE TITLE
Android Auto integration

### ISSUE THREAD

**Issue by th0mcat** [SchildiChat/SchildiChat-android#59]
Copying some stuff from [element-android, #240](https://github.com/vector-im/element-android/issues/240)

> It would be great to support Android Auto. Especially for notifications.
> 
> I tried declaring android auto support in the manifest https://developer.android.com/training/cars/messaging#manifest-messaging but it didn't seem to work. I thought that with the notifications now using MessagingStyle we would get Android Auto support for free.
> 
> Maybe someone else could test.
> 
> was previously requested for riot-android as:
> vector-im/riot-android#2811
> vector-im/riot-android#698

...

> For reference, [Here is Signal's implementation](https://github.com/signalapp/Signal-Android/commit/9148b7da5f4604dae1106d3932bfa7d3bfa63ad4) of Android Auto integration.  [Here's](https://github.com/iNPUTmice/Conversations/pull/2441/files/403eff3d19df8111b73e6edfce91c2f95ee4d785) another implementation from an XMPP client called "Conversations"

I'll gladly send a donation to whomever implements this.

**Comment by th0mcat** [comment]
This is now upstream as of https://github.com/vector-im/element-android/pull/4252.

**Comment by SpiritCroc** [comment]
Cool!
