### ISSUE TITLE
RTL Bubble Layout Jankiness

### ISSUE THREAD

**Issue by anaskaejdar** [SchildiChat/SchildiChat-android#61]
**Describe the bug**
If the app is set in an RTL language, such as Farsi or Arabic, some parts of the UI become clunkier.  I'm talking about missing padding, timestamps always being on a new line.  I've only noticed those two things so far.

**To Reproduce**
1. Put app in farsi
2. Go into a chat
3. Look at the padding on your own messages
4. Look at the timestamps on all the messages

**Expected behavior**
Timestamps should be on the same line as the message, given that it can fit, but it's instead being put on its own new line.  It's worth noting that actually the timestamp gets rendered perfectly well if the message itself is written in an RTL language.

**Screenshots**
Message in farsi, with an immaculate timestamp:
![Screenshot_۲۰۲۱۰۵۱۶-۱۹۵۷۱۷_SchildiChat](https://user-images.githubusercontent.com/32847759/118427698-aed30200-b682-11eb-91f9-0d1464d3d24c.jpg)

Messages in english.  Notice the padding on the left side too:
![Screenshot_۲۰۲۱۰۵۱۶-۲۰۰۰۰۹_SchildiChat](https://user-images.githubusercontent.com/32847759/118427735-c6aa8600-b682-11eb-90b6-823b25f099ce.jpg)

same messages if app is in a LTR language:
![Screenshot_۲۰۲۱۰۵۱۶-۲۰۰۰۵۱_SchildiChat](https://user-images.githubusercontent.com/32847759/118427777-da55ec80-b682-11eb-80f1-28e912d24921.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung GS20
 - OS: Android 11

**Additional context**
 - App version and store: 1.1.3.SC30 FDROID
 - Homeserver: ostavrosnika.com

**Upstream relevance**
 - Does this issue exist in Element Android? No, it's particular to schildi's layout
 - If this issue exists in Element Android, please also link the corresponding bug report (create a new one if it doesn't exist yet)

Álo 👋🏼

**Comment by SpiritCroc** [comment]
Thanks for reporting! Those issues will be addressed in the next release. If you notice issues in the next release as well, feel free to open a new issue or re-open this one.

**Comment by anaskaejdar** [comment]
@SpiritCroc Thank you, man.  It came into fdroid a couple days ago, and it looks great.  There is one other layout bug I found.  Here, take a look:

RTL:

![Screenshot_۲۰۲۱۰۶۰۱-۱۷۰۷۰۴_SchildiChat](https://user-images.githubusercontent.com/32847759/120405286-13d25d00-c2fd-11eb-9e82-b9864e1e9ecf.jpg)
![Screenshot_۲۰۲۱۰۶۰۱-۱۷۱۲۱۰_SchildiChat](https://user-images.githubusercontent.com/32847759/120405302-1b920180-c2fd-11eb-8a5e-989a9c480417.jpg)


LTR:

![Screenshot_۲۰۲۱۰۶۰۱-۱۷۰۷۴۳_SchildiChat](https://user-images.githubusercontent.com/32847759/120405321-251b6980-c2fd-11eb-84a3-2a9cb71c4a5e.jpg)
![Screenshot_۲۰۲۱۰۶۰۱-۱۷۱۳۳۷_SchildiChat](https://user-images.githubusercontent.com/32847759/120405328-2a78b400-c2fd-11eb-831c-17cf41222e60.jpg)


Obviously the first one is caused by that long username pill.  No such pill on the second one though.
