### ISSUE TITLE
[BUG] Schildichat keeps doing the inital sync every few days

### ISSUE THREAD

**Issue by ghost** [SchildiChat/SchildiChat-android#62]
Every few days Schildichat does the inital sync again,
i dont log out or anything i just open the app and it does the inital sync again, it doesnt normally take longer then a minute

![Screenshot_20210518-084643](https://user-images.githubusercontent.com/78061111/118672486-4725cf80-b7c6-11eb-9f36-ebbc630bff00.png)

**Comment by SpiritCroc** [comment]
Can you reproduce this issue with the same account on Element Android? If not, can you send a rageshake when it happens next time?

**Comment by ghost** [comment]
> Can you reproduce this issue with the same account on Element Android? If not, can you send a rageshake when it happens next time?

This issue (so far) seems to be nonexistent in version 1.1.7sc32, 
Sometimes when opening Schildichat i see the initial sync icon flash in the notification bar for a second then it disappears.

**Comment by SpiritCroc** [comment]
The notification is probably the "listening for events" notification, which is not limited to initial syncs. Great to hear it seems fine now!

**Comment by ghost** [comment]
@SpiritCroc it happened again and i sent a Rageshake

**Comment by SpiritCroc** [comment]
Thanks! There are some `Out of memory` errors in there. Could it be that your device is low on RAM or disk space?

**Comment by ghost** [comment]
> Thanks! There are some `Out of memory` errors in there. Could it be that your device is low on RAM or disk space?

My device definitely isnt low on disk space, but it only has 1.5G of RAM and Schildichat did crash just before the inital sync happened this time, so my device could have been low on RAM.

**Comment by SpiritCroc** [comment]
Related upstream issue: https://github.com/vector-im/element-android/issues/2841

**Comment by darkmorpher** [comment]
Is this still reproducible on current release [v1.4.34.sc58](https://github.com/SchildiChat/SchildiChat-android/releases/tag/sc_v1.4.34.sc58) ?
