### ISSUE TITLE
Another RTL Margin Bug

### ISSUE THREAD

**Issue by anaskaejdar** [SchildiChat/SchildiChat-android#66]
I originally made this as a response to a different issue, a closed one I made before.  I couldn't reopen the issue, though, I think I don't have the necessary privs.  Feel free to close this and open that: https://github.com/SchildiChat/SchildiChat-android/issues/61#

RTL:

![Screenshot_۲۰۲۱۰۶۰۱-۱۷۰۷۰۴_SchildiChat](https://user-images.githubusercontent.com/32847759/120405286-13d25d00-c2fd-11eb-9e82-b9864e1e9ecf.jpg)
![Screenshot_۲۰۲۱۰۶۰۱-۱۷۱۲۱۰_SchildiChat](https://user-images.githubusercontent.com/32847759/120405302-1b920180-c2fd-11eb-8a5e-989a9c480417.jpg)

LTR:

![Screenshot_۲۰۲۱۰۶۰۱-۱۷۰۷۴۳_SchildiChat](https://user-images.githubusercontent.com/32847759/120405321-251b6980-c2fd-11eb-84a3-2a9cb71c4a5e.jpg)
![Screenshot_۲۰۲۱۰۶۰۱-۱۷۱۳۳۷_SchildiChat](https://user-images.githubusercontent.com/32847759/120405328-2a78b400-c2fd-11eb-831c-17cf41222e60.jpg)

Obviously the first one is caused by that long username pill.  No such pill on the second one though.

_Originally posted by @maemunman in https://github.com/SchildiChat/SchildiChat-android/issues/61#issuecomment-852585873_

**Comment by SpiritCroc** [comment]
I was able to reproduce the long pills issue, but not the other one, not sure why. Either way, please test and report if it's better once 1.1.8 is out.

**Comment by anaskaejdar** [comment]
The second one only happens on certain messages.  I don't know what the pattern is.  You may find it if you scroll back far enough in a room though.

**Comment by anaskaejdar** [comment]
I haven,t encountered it in a while, I think maybe it's fixed
