### ISSUE TITLE
Unified push

### ISSUE THREAD

**Issue by SpiritCroc** [SchildiChat/SchildiChat-android#68]
Might be worth to try out, if the Element team does not look into it earlier:
https://github.com/vector-im/element-android/pull/3448

**Comment by atuctuc** [comment]
would be great, i just tested unified push with fluffy chat, thats what i was waiting for, it's really super, only the voip (ringing) function is missing, hope we will have soon unified push support in schildichat!!

**Comment by SpiritCroc** [comment]
> would be great, i just tested unified push with fluffy chat, thats what i was waiting for, it's really super, only the voip (ringing) function is missing, hope we will have soon unified push support in schildichat!!

We're already testing it internally, it works great, but there are some details that we'd like to address before including it in release builds.

**Comment by genofire** [comment]
The F-Droid testing works well, thanks for creating one
