### ISSUE TITLE
Hide avatars and usernames in DM chats

### ISSUE THREAD

**Issue by Bubu** [SchildiChat/SchildiChat-android#7]
This is something Telegram does and I actually never noticed this until I started using other bubble messaging apps that didn't do this.

In a DM chat you have just the bubbles coming from left and right side in different colors but the user avatars and the user name (on top of the bubble normally) are hidden because this is really redundant information. This makes for a cleaner DM chat experience.

**Comment by SpiritCroc** [comment]
The main reason why I don't want to hide the usernames is that the bubbles look weird if they only have the timestamp in it on the top. Telegram circumvents this by putting the timestamp below the message content, or right at the end of the last line if there is space, but I don't know how easy it is to implement this.

Hiding the avatars should probably work, I put this on my TODO (somehow I thought it was already there, but seems like it got lost).

**Comment by SpiritCroc** [comment]
Avatars are now hidden with above commit. To hide usernames while still showing timestamps, I'd need to do some bubble redesign to make it look ok, so that might justify a new issue, if necessary (but my motivation is not very high in that regard right now).
