### ISSUE TITLE
I can't see typing indicator when people chat for bridge to facebook

### ISSUE THREAD

**Issue by AnisTaluqdar** [SchildiChat/SchildiChat-android#71]
As I said in title I can't see typing indicator on android which is bridge from facebook. it's worked in element but don't work in Schildichat.

I tested it in my android app only.

**Comment by SpiritCroc** [comment]
SchildiChat shouldn't differ from Element in this regard. Have you compared matching versions?

**Comment by AnisTaluqdar** [comment]
both are latest android version

**Comment by SpiritCroc** [comment]
Which is? ("latest version" is not a valid response for me, as different stores vary in speed for providing new updates, and Element releases remain in beta testing for some time...)

**Comment by AnisTaluqdar** [comment]
Element Version: 1.1.11
SchildiChat Version: 1.1.11.sc36

**Comment by SpiritCroc** [comment]
So to understand the issue: you say that the typing indicator from people typing on the facebook side doesn't show up in SchildiChat, but shows up in Element? And other typing indicators in general show up in SchildiChat?

**Comment by AnisTaluqdar** [comment]
Yes, not only Facebook, from any bridge network don't work in SchildiChat but works in Element. Yeah but for general network like matrix it works in SchildiChat too.

**Comment by SpiritCroc** [comment]
Hm, I still find it unlikely that missing typing indicators from bridges is a client bug, or that SchildiChat would differ from Element in that regard. But I'll see if I can observe similar behavior for my bridges.
