### ISSUE TITLE
Every time when I open the app it's sync.

### ISSUE THREAD

**Issue by AnisTaluqdar** [SchildiChat/SchildiChat-android#72]
It's really painful. And I know all of the matrix clients do it. So, is it possible to do sync in the background? 
It will be a great thing if you can add it to the background process and when we will open the app will show up the instant without delay.

**Comment by SpiritCroc** [comment]
I don't get why you ask questions in #schildichat-android:matrix.org and then leave the room before I answer, now the second time... if you found a bug, post it here, no need to also post in the room. If you have a question, ask in the room, and don't expect we'll answer immediately after that, we do this in our free time and have other things to do as well.

Do you get initial sync like in this issue? https://github.com/SchildiChat/SchildiChat-android/issues/62
Or are you referring to the small progress bar above the room list?

**Comment by AnisTaluqdar** [comment]
Oh, understandable. I meant small progress bar above the room list. every time it's  loading.

**Comment by SpiritCroc** [comment]
Doing too much work in background would cause a bad impact on battery life, and will likely also be prohibited by the Android operating system for that reason. The app is usable while this sync is in progress, so it's not a big issue to me either way.
