### ISSUE TITLE
Failed to import key after Reset keys

### ISSUE THREAD

**Issue by ghost** [SchildiChat/SchildiChat-android#75]
**Describe the bug**
After pressing the Reset key button then enter the Recovery phrase it returns a 'Failed to import keys` error.

**To Reproduce**
1. resetting the keys at `Settings->Security & Privacy->Cross-Signing->Reset keys`.
2. it asked for Recovery Passphrase.
3. i entered it.
4. it returned this image:
![Screenshot_20210724-133958_SchildiChat.jpg](https://user-images.githubusercontent.com/16048625/126868906-1993194e-cf47-4bca-9c9d-a2d90e51da38.jpg)

**Expected behavior**
New session gets verified and move on.

**Screenshots**
![Screenshot_20210724-133958_SchildiChat.jpg](https://user-images.githubusercontent.com/16048625/126868906-1993194e-cf47-4bca-9c9d-a2d90e51da38.jpg)
![Screenshot_20210724-135231_SchildiChat.jpg](https://user-images.githubusercontent.com/16048625/126869017-3bc24d2a-fdf8-4f8e-bd8e-4f545ebe01c8.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung M31
 - OS: Android 11

**Additional context**
 - App version and store: 1.1.11.sc36 [40100530] (F-1ba30d4b) - Fdroid
 - Homeserver: halogen.city

**Upstream relevance**
 - Does this issue exist in Element Android? Don't know
 - If this issue exists in Element Android, please also link the corresponding bug report (create a new one if it doesn't exist yet)

**Comment by SpiritCroc** [comment]
While I haven't found a similarly described issue for Element Android, I'd still assume it's an issue from them, since I did not change anything related as far as I'm aware. If (and only if) you can reproduce this on SchildiChat and not on Element for the same version, I'd be interested in a rageshake/bug report from within the app.

**Comment by ghost** [comment]
I understand.
On the topic of reproducing on element, i cant do it due to limited space and hardware on my device.
