### ISSUE TITLE
Sticker rendering improvements

### ISSUE THREAD

**Issue by Bubu** [SchildiChat/SchildiChat-android#8]
Stickers could be rendered a bit bigger and probably shouldn't have a bubble around them. (And big emojis probably shouldn't either, as I consider them sticker equivalents mostly)

Comparison
![Screenshot_20200902-151906_SchildiChat](https://user-images.githubusercontent.com/105185/91989089-6102ad80-ed30-11ea-89ff-820c7b643bc3.png)
![Screenshot_20200902-151846_Telegram_FOSS](https://user-images.githubusercontent.com/105185/91989097-63650780-ed30-11ea-964a-22eb84b5befe.png)

**Comment by SpiritCroc** [comment]
Probably makes sense, I put this on my TODO to try out.
