### ISSUE TITLE
Unread messages counting number is not visible.

### ISSUE THREAD

**Issue by realgrm** [SchildiChat/SchildiChat-android#80]
**Describe the bug**
Unread messages counting number is not visible.
Sometimes the smaller circle where the counting would be is also not visible.

**To Reproduce**
1. Enable Settings>Labs>Opens at first unread
1. Open an conversation with unread messages

**Expected behavior**
Unread messages counting number to be visible.

**Screenshots**
![Screenshot_20210823-102443](https://user-images.githubusercontent.com/23300290/130455852-25e5edaf-909a-4311-9266-6e80902c7900.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus 7
 - OS: Oxygen OS 11.0.2.1.GM57AA
 - Android Version: 11

**Additional context**
 - App version: 1.2.0.sc41 [40100630] (G-5f18fce7)
 - Store: Play Store
 - Homeserver: matrix.org
 
Issue inside the app opened:
- Matrix ID: realgrm
- When: something between 23/08/2021 10:24 to 10:34

**Upstream relevance**
 - Feature currently exclusive to Schildichat

**Comment by SpiritCroc** [comment]
Unfortunately / as far as I know, matrix doesn't provide us any unread message counters right now - what you see in some rooms are unread notification counters, which only work in chats that you haven't muted.

Thus, in your screenshot, you can see a small red dot on the top right of the bigger button which indicates an indeterminate number of new messages. I agree that there is probably some better way to indicate this (i.e., accent color dot on an accent color button is not a great choice, this happened by accident when I changed the button color compared to Element, but not the indication dot). I have not decided yet on how I'd like it to look though.

Can you confirm this happened for you in a chat that you have muted?
