### ISSUE TITLE
Voice messages

### ISSUE THREAD

**Issue by tehw0lf** [SchildiChat/SchildiChat-android#81]
Since SchildiChat is based on Element which has voice message support for some weeks, I'm wondering whether this option will be added/enabled in SchildiChat as well.

Or is the feature already implemented and I did just not find it?

Otherwise I'm really happy with the app, but voice messages would be one step further towards migrating to matrix completely.

**Comment by tipanic** [comment]
The voice message feature is already implemented for the android app, but not for the web application (element has it on both)
And another problem is, that you can only hear the messages with loudspeakers, but not with the internal speaker, its still on loudspeaker when you put it to your ear. 
Oh and i forgot, you can't skip inside the message, you can only start it from the beginning.

**Comment by tehw0lf** [comment]
Thanks for the reply!

But is it already implemented in the SchildiChat android app? I have the latest version from F-Droid and couldn't find a way to send a voice message instead of a text message. Maybe my own matrix server is also missing some configuration then.

Also I am aware that the element feature is still rather new and full of bugs, I'm just hyped for this feature and wanted to try it :)

**Comment by tipanic** [comment]
Yes, it is already implemented in the SchildiChat android app (i use the google play version 1.2.0.sc41), i have my own matrix server running, and i didn't had to tweak my config to use ist. Its a simple button like in whatsapp on the far right next to the paperclip button.

**Comment by tipanic** [comment]
Ah, its an experimental feature, maybe its deactivated in your app, check your settings please

**Comment by tehw0lf** [comment]
Perfect, thanks a lot!

F-Droid is still on 1.0.10.sc25!

That's really no problem for me though as I can wait for those few versions.

I've checked the "Lab" which so far only has the 'swipe to reply' functionality.

I'll close this issue as resolved though now as you've completely answered my question(s).

Thanks a lot for this great app :)

**Comment by su-ex** [comment]
Duplicate of https://github.com/SchildiChat/SchildiChat-android/issues/20

**Comment by SpiritCroc** [comment]
FYI: voice message recording has been disabled on Android 5.0, as it was not working on that Android version - so in case any Android 5.0 user discovers this issue, that's the reason why the button is hidden. (In case you're an Android 5.0 user and voice messages are not broken on Element Android for you, please report so I can re-enable it)
