### ISSUE TITLE
SSL Error when logging in

### ISSUE THREAD

**Issue by fummymint** [SchildiChat/SchildiChat-android#82]
**Describe the bug**
I get SSL Error when I log in. I am using matrix.org as my server.

**To Reproduce**
1. login
2. see ssl error.

**Expected behavior**
can't login.

**Screenshots**
![Imagepipe_1](https://user-images.githubusercontent.com/56063272/132091643-c1b75b22-f488-4084-a3a7-a18ab6dcc768.jpg)

**Smartphone (please complete the following information):**
 - Device: OP8T(Kebab)
 - OS: LOS 18.1(Android 11)

**Additional context**
 - App version and store: f-droid 1.2.0.sc41 beta(f) and playstore 1.2.0.sc41 
 - Homeserver: matrix.org

**Upstream relevance**
 - Does this issue exist in Element Android?
 yeah it happens on element android client too
 - If this issue exists in Element Android, please also link the corresponding bug report (create a new one if it doesn't exist yet)
n/a
I can log in fine in schildichat web, but can't on any android client. switching from my wifi to data connection fixes the issue.

**Comment by SpiritCroc** [comment]
Sounds to me like your wifi router is doing some shady things.
What happens for you in your wifi when opening https://matrix-client.matrix.org/_matrix/federation/v1/version from your browser? Is it a public wlan?
