### ISSUE TITLE
Rejecting an invite doesn't make it disappear

### ISSUE THREAD

**Issue by phesch** [SchildiChat/SchildiChat-android#83]
**Describe the bug**
Sometimes(?), rejecting an invite doesn't cause that invite to go away from the main screen.
The rejection was definitely sent, because checking with another client (Element Desktop) doesn't show it anymore.
Selecting "Reject" again just makes the spinner reappear until navigating somewhere else.
Coming back will show the buttons again.
Performing an initial sync will make the invite disappear.

**To Reproduce**
1. Get an invite (to a DM in this case).
2. Select "Reject" on the main screen.
3. The spinner appears, but the invite doesn't go away.
4. Coming back later still shows the invite.

**Expected behavior**
After selecting "Reject", the invite should go away after a brief period of time.

**Smartphone (please complete the following information):**
 - Device: LG G8s ThinQ
 - OS: Android 10

**Additional context**
 - App version and store: v1.2.0.sc41 from F-Droid
 - Homeserver: Conduit 0.2.0

**Upstream relevance**
 - I don't know whether this occurs with Element Android as well.

**Comment by darkmorpher** [comment]
Is this still reproducible on current release [v1.4.34.sc58](https://github.com/SchildiChat/SchildiChat-android/releases/tag/sc_v1.4.34.sc58) ?

**Comment by phesch** [comment]
Sorry it took me so long to get back to you - the notification for your comment got lost in my inbox :/

I just checked by creating a new room with a secondary account and inviting my first account to it, then rejecting that invite from SchildiChat. It shows the same behavior as described in my original report.
I tested this on version v1.5.8.sc62, which is the version currently available on F-Droid.

**Comment by phesch** [comment]
I was just checking my server's proxy access logs when I noticed the following line (logged at the time I performed the test):
```
<IP> - - [<TIME>] "GET /_matrix/client/r0/rooms/!<ROOM_ID>:matrix.org/members?at=1051519&not_membership=LEAVE HTTP/1.1" 403 114 "-" "SchildiChat/1.5.8.sc62 (LGE LM-G810; Android 12; SKQ1.211103.001; Flavour GooglePlay; MatrixAndroidSdk2 1.5.8)" "-" 582 0.015
```
Maybe this could be a hint as to the cause?

**Comment by SpiritCroc** [comment]
Latest stable release is quite old, maybe worth trying again once we'll get a new release in the coming days (I hope).
Either way, I haven't really touched any related code as far as I'm aware, so it's likely either an Element issue or a conduit issue.
