### ISSUE TITLE
UP: Automatically use custom push gateway if possible

### ISSUE THREAD

**Issue by jacktheripper19** [SchildiChat/SchildiChat-android#85]
**Is your feature request related to a problem? Please describe.**
- After implementing UnifiedPush, the app is using the dev push gateway at http://up.schildi.chat/_matrix/push/v1/notify for pushing notification. There is a number of people who are using UnifiedPush and are self hosting their own distributor instance like Gotify-UP along with common-proxies that can serve as a push gateway according to https://github.com/UnifiedPush/contrib/blob/main/gateways/matrix.md . Therefore there is no need for them for an external push gateway.
**Describe the solution you'd like**
- Having the ability to set up the push gateway or automatically detect if the hosted Gotify server can handle the path /_matrix/push/v1/notify through Gotify client and using to it.
**Describe alternatives you've considered**
- As a workaround, pointing the used http://up.schildi.chat/ to the ip/domain of the self hosted push gateway in client's  /etc/hosts file or through a dns rewrite. However, one needs to deal with ssl certificates which is a pain, otherwise you get ssl error on the app.
**Additional context**
- The implementation of this would be a function on Schildichat that requests /_matrix/push/v1/notify on user endpoint to see if there is a working  gateway on the defined server whether it is the schildi one or the self hosted one.
- Other matrix client Fluffychat uses unifiedpush server if it can't find the gateway on the provider domain

**Comment by SpiritCroc** [comment]
Right, [that one is TODO](https://github.com/SchildiChat/SchildiChat-android/blob/9211d3c4d94e7b8b1697b9e201ca37039ae55df4/vector/src/main/java/im/vector/app/core/pushers/UPHelper.kt#L156-L160)

**Comment by SpiritCroc** [comment]
Next release will have a labs setting to force using the endpoint as gateway (commit https://github.com/SchildiChat/SchildiChat-android/commit/b96f150dd01b6a5e821112b2c344d76e124d77c9). We can keep this issue open for automatic detection.

**Comment by youphyun** [comment]
This is the "Force custom push gateway" setting right? I confirm I have it enabled. I have a default Gotify server running using docker on Debian 11 with the [UnifiedPush nginx lua rules](https://unifiedpush.org/users/distributors/gotify/) + [Matrix-specific re-write proxy](https://gitlab.com/famedly/fluffychat/-/tree/v0.42.1#matrix-specific-re-write-proxy). Latest seems a better workaround then the dns-etc/hosts workaround described above. Note that I need to re-register the push distributor multiple times to get the correct push_key + url visible in SchildiChat pointing to my own gotify server. Still no luck with the notifications, what could be wrong?

<img src="https://user-images.githubusercontent.com/12627719/151697026-896722cd-0fd3-461a-80a8-ccf7f2751acb.png" width="250">

**Comment by SpiritCroc** [comment]
Automatic detection has been implemented by upstream for a while now.
