### ISSUE TITLE
Replying or posting while being far into the timeline.

### ISSUE THREAD

**Issue by FUS132** [SchildiChat/SchildiChat-android#86]
**The bug**
If you're too far into the old messages, and try to reply to said old messages or post something, it will not go through as if you haven't posted anything.

**To Reproduce**
Steps to reproduce the behaviour:
1. Scroll far into the old messages in a busy chat room (may also be dependant on whether the new messages are pre-loaded or not, but I'm not certain);
2. Try to reply or post something;
3. Check for a message by going to the newer messages;
4. It's usually isn't there.

**Expected behaviour**
Messages should go through regardless of the user's position on the message timeline.

**Smartphone (please complete the following information):**
 - Device: Huawei Honor 6a
 - OS: Android 7.0 Nougat

**Additional context**
 - App version and store:1.2.2.sc43, from Play Market
 - Home server: Matrix.org

**Upstream relevance**
 - Does this issue exist in Element Android? - Doesn't appear to be.

**Comment by SpiritCroc** [comment]
Unable to reproduce so far. Also, "Latest version" ist not a valid version.

**Comment by FUS132** [comment]
> Unable to reproduce so far. Also, "Latest version" ist not a valid version.

My bad, the app version is 1.2.2.sc43.
