### ISSUE TITLE
Question about Unified Push

### ISSUE THREAD

**Issue by bahur142** [SchildiChat/SchildiChat-android#87]
Hello developers of Schildi Chat.
Sorry for opening ticket in your issue tracker, but I don't know where to ask a question about UP. Feel free to close it.

I've managed to do my own fork of Element Android about an year ago. Using also self-hosted push server Sygnal for delivering pushes. Last days I am reading some publications about Unified Push and looking forward on how can I use it.
Since Element still not provide UP, I am looking at your application Schildi Chat and see that you have implemented successfully UP. Since I am not a programmer and did not understand Java/Kotlin (though I have my own fork), want to ask about the following commit:
https://github.com/SchildiChat/SchildiChat-android/commit/a3a946fb750b4186797cc97af7f17fbdce458496#diff-44923f4e9b5a6e14764ee8b524a9d8afaeb48ac8f6cb8d708b0794965c557692
If I use the code of these 24 changed files at the time of commit, can I build successfully a version of my own Element with UP support? Is it enough to support UP only with this commit and the files changed?

**Comment by SpiritCroc** [comment]
For building Element with unified push, easiest would be just using this PR: https://github.com/vector-im/element-android/pull/3448
SchildiChat's UP implementation is also based on that PR.
