### ISSUE TITLE
Add Build Metadata F-Droid

### ISSUE THREAD

**Issue by ByteBitten** [SchildiChat/SchildiChat-android#89]
I noticed F-Droid has a 'Matrix' category and SchildiChat isn't in there.

For more people to find the app and become users, I suggest adding the 'Matrix' category to the metadata to get it in there.

[F-Droid build documentation](https://f-droid.org/en/docs/Build_Metadata_Reference/)

**Comment by SpiritCroc** [comment]
Are you sure this is an official category? The only app on my device that seems to use this category is FluffyChat, which does not exist in the official F-Droid repository right now.

**Comment by ByteBitten** [comment]
Ah, I seem to have overlooked that.
I do have FluffyChat repo added.

And with the main repo only accepting the set categories, Matrix being a Communication 'sub-category'; there seem to be no use for my request...
As I do believe starting a request for Matrix to be a main F-Droid category would be a cascading trigger for other platforms like Mastadon, PeerTube, etc... So; very small chance that would fly.

Too bad :(

**Comment by SpiritCroc** [comment]
Either way, this should rather be an issue for the F-Droid repo than this repo.
