### ISSUE TITLE
Real-time voice notes with automatic playback

### ISSUE THREAD

**Issue by discapacidad5** [SchildiChat/SchildiChat-android#92]
This issue seems to suggest following (correct me if I'm wrong):

- Automatic playback mode for voice messages when they arrive.
- Play all voice notes after each other
- Play voice message of other person while they are still recording it (note: why not just use a "call" :thinking:)

tl;dr part:

#### What would you like to do?

I would like to be able to send a voice note that is heard in the same moment that I am recording it in real time. I would also like to be able to listen to the voice notes without having to think about each note, but rather that they play automatically as it arrives.

#### Why would you like to do it?

Many times one wants to interact or listen to the conversation in a chat. But one is busy working, or has dirty hands and I can't be touching the phone to play every voice memo. If there is an option that allows voice memos to be played automatically one can be listening to the chat conversation while busy doing something else without having to have the phone in hand or you are playing every so often to hear the new note

#### How would you like to achieve it?

I would like there to be some button that will activate the automatic playback of the voice notes and that the voice notes will be played while they are recording. This would speed up the time more because normally one recorded a voice note of 2 minutes deep minutes that it takes to record after the person takes a few seconds to download and 2 minutes to play it is 4 minutes in a single voice note row voice note is played while recording the time becomes shorter and communication faster this could be achieved if the voice memo is transmitted extreming

#### Have you considered any alternatives?

An alternative could be an integrations that places a walkie-talkie-style ptt button that anyone who steps on that button transmits live audio to all members of the room.

#### Additional context

This function would be something very practical and useful at this time where the voice conversation is being handled a lot in real time, this allows you to stay connected all the time and the listener will be while you are busy working doing anything of the entire conversation in your room such as If it were a radio station, the consumption is also lower since everyone can listen but not everyone speaks at the same time, so there is less consumption than in a continuous call and fewer disturbances, each person steps only when they want to speak

**Comment by su-ex** [comment]
And btw, real time voice messaging has already been possible some decades, it's called telephony. So just make a phone call! ☎️

**Comment by discapacidad5** [comment]
a call is not the same as a voice message
 calls do not keep a record voice messages are saved to listen to as many times as you want. they are heard in real time the first time, then you can play them normally as many times as you want

On the other hand, the call stays active all the time, capturing the constant sound in a single continuous audio, voice messages are only transmitted when you press the button to speak

in a call everyone speaks at the same time in the voice message only one person speaks and everyone else listens

so there is a very noticeable difference between one thing and another



> ¡¿También Android, supongo?!?

Yes

**Comment by su-ex** [comment]
I transferred this to Android.

**Comment by discapacidad5** [comment]
> Transferí esto a Android.

I think this applies to all versions. and for the desktop version even more, you can listen without having to be seated at the computer

**Comment by SpiritCroc** [comment]
I tried to clean up the issue a little. But still, it is hard to read, and proposes too many things at once. I'll close this issue - if these suggestions are important to you, feel free to open individual issues (one proposal per issues).

I'm not really interested in implementing such features though (a "call" would be a suitable solution in my opinion) - but I guess I'm open for contributions.
