### ISSUE TITLE
accent colour is used incorrectly in some places (online indicator, verification shield color)

### ISSUE THREAD

**Issue by Bubu** [SchildiChat/SchildiChat-android#97]
**Describe the bug**
if you set red as your accent colour, contacts that are online will be shown with a red dot. similarly a red shield now means "verified". :see_no_evil: 

This is also tricky with the default color, as the verification shield in element has a different green colour but it explicitly ask you that both shields look the same... which has created some user-confusion in the past.

**To Reproduce**
* Set a red theme accent color

**Expected behavior**
certain elements retain their default colours.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Nexus 5X
 - OS: LOS 15.1

**Additional context**
 - App version: latest beta
 - Store: SpiritCroc's F-Droid
 - Homeserver: any

**Upstream relevance**
 - Does this issue exist in Element Android? no

**Comment by SpiritCroc** [comment]
I guess we should probably use the Schildi-default-green for verification across all SC themes, so it at least matches Schildi-Desktop (no, I don't want to use Element green anywhere for the Schildi themes).

For the presence indicator, I don't think it's much of an issue... if you choose red as accent color, you surely want red to be more than just a color for warnings, don't you?

**Comment by Bubu** [comment]
> I guess we should probably use the Schildi-default-green for verification across all SC themes, so it at least matches Schildi-Desktop (no, I don't want to use Element green anywhere for the Schildi themes).

I think that's fair.

> For the presence indicator, I don't think it's much of an issue... if you choose red as accent color, you surely want red to be more than just a color for warnings, don't you?

I honestly don't know. On the one hand... yes, it kind of fits the theming. On the other hand it *is* quite confusing I think. Red status indicator immediately says *BUSY!* to me :man_shrugging:. Maybe doing some testing with this would help figuring this out.

**Comment by SpiritCroc** [comment]
> I honestly don't know. On the one hand... yes, it kind of fits the theming. On the other hand it _is_ quite confusing I think. Red status indicator immediately says _BUSY!_ to me man_shrugging. Maybe doing some testing with this would help figuring this out.

Hm, I see your point. Would you suggest using the SC green for presence in all SC themes, or only in the red theme?

**Comment by Bubu** [comment]
All yellow-ish, orange-ish and reddish accent colours will clash with some preconceived status notion. (yellow/orange -> away).

The blue-ish and purple ones are likely fine. It might still be a bit confusing what a purple status is supposed to mean, but at least I wouldn't know what else this could be confused with.

Edit: After trying out purple for a bit, I think that this looks fine as is :-).

**Comment by fynngodau** [comment]
I think this would be a good solution: all of the five colors in the first color selection row, plus maybe the last Lava color, seem unfit to be used as an „available” status indicator. For all other colors it is slightly confusing at first, but ultimately fits the theme better.
