### ISSUE TITLE
Successful verifications aren't stored (shield stays black)

### ISSUE THREAD

**Issue by jaller94** [SchildiChat/SchildiChat-android#98]
**Describe the bug**
Even after successfully verifying a person, their verification shield stays black.

**To Reproduce**
1. Verify a user.

I tested when
 * the other person was on the same homeserver and a different one
 * the other person was using Element, SchildiChat and FluffyChat
 * the other person had their QR scanned, the other person scanned my QR code and we compared emojis.

All variations of this verification flow seem to be affected.

Navigating out of the chat and back into it does not make the shield turn green.
Clearing the cache of SchildiChat does not make the shield turn green.

**Expected behavior**
The other person is now successfully verified and a green shield shows up next to their Display Name.

**Smartphone (please complete the following information):**
 - Device: OnePlus 5
 - OS: Android 10

**Additional context**
 - App version: 1.3.6.sc46 [40100700] (F-bd681432)
 - Store: F-Droid
 - Homeserver: matrix.org

**Upstream relevance**
 - The issue does not exist on Element Android.

**Comment by SpiritCroc** [comment]
>     * The issue does not exist on Element Android.

I'd be surprised. Our logic should not differ to theirs. For example, https://github.com/vector-im/element-android/issues/1377 and https://github.com/vector-im/element-android/issues/3169 look similar.

**Comment by jaller94** [comment]
Both linked issues seem to be about the verifying your own devices.
This issue is about verifying other people.

On my Android phone I have the same account logged into SchildiChat and Element. Only with Element the verifications are persisted (= my device shows a green shield for their account).

**Comment by SpiritCroc** [comment]
I tried now following on some of my Schildi-Androids with base-version 1.3.6:

- Start verification on Schildi-Android, and use Android to scan a QR on schildi-desktop of a user on a different homeserver
- An emoji-based verification between two Schildi-Androids, with users on different homeservers

Both worked for marking each other as verified.

Are there any chances your SchildiChat and your Element Android differ in some cross-signing setup?
I know this might be a little annoying to test, but it might be interesting too to compare a fresh install of SchildiChat with a fresh install of Android of the same Element-Android-version, just to be sure.

**Comment by loomy** [comment]
same here with android 11 and the fdroid version 1.4.20.sc55

shields in rooms are always black. they are not getting green nor red, whats even worse.

@SpiritCroc  have you tested with the fdroid version ?

**Comment by SpiritCroc** [comment]
> same here with android 11 and the fdroid version 1.4.20.sc55
> 
> shields in rooms are always black. they are not getting green nor red, whats even worse.
> 
> @SpiritCroc have you tested with the fdroid version ?

Yes, I'm almost always on fdroid versions these days. But that shouldn't make any difference for this matter either way.

**Comment by loomy** [comment]
ok. but seems to be a factor in our case. 
we are 3 users fresh set up of server and clients. 2 users are on fdroid schildi, one is on google play schildi.
the google play user has green shields for users an chats. the two fdroid users have black shields.

**Comment by SpiritCroc** [comment]
I'd still assume the differences to be rather account-specific or login-specific (e.g. some broken secure backup or verification state), unless there's clear evidence that there's a difference in variants here (i.e. you can install the same version number with different variants repeatedly on the same device with the same account and same setup procedure and get reliably said difference).

**Comment by jaller94** [comment]
It's 12 months old and I don't remember this coming up again.
Closing as "can't reproduce".
